import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Airplay,
  AlarmClock,
  Anchor,
  Apple,
  Archive,
  Armchair,
  Award,
  Backpack,
  Banknote,
  BarChart3,
  Bed,
  Bell,
  Bike,
  Binoculars,
  Book,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Building2,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  CheckSquare,
  Cherry,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Computer,
  Cookie,
  Crown,
  Database,
  Dog,
  Dumbbell,
  Egg,
  Flame,
  FlaskConical,
  Flower2,
  ForkKnife,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  IceCreamBowl,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Moon,
  Mountain,
  Music,
  PaintBucket,
  Palette,
  PartyPopper,
  PawPrint,
  Pen,
  PiggyBank,
  Plane,
  Podcast,
  Puzzle,
  Rocket,
  Sailboat,
  Shield,
  ShoppingCart,
  Skull,
  Smartphone,
  Smile,
  Snowflake,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Sword,
  Telescope,
  Tent,
  Timer,
  Trophy,
  Umbrella,
  Utensils,
  Video,
  Watch,
  Waves,
  Weight,
  Wheat,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export const BOARD_ICONS: { name: string; icon: LucideIcon }[] = [
  { name: "Activity", icon: Activity },
  { name: "Airplay", icon: Airplay },
  { name: "AlarmClock", icon: AlarmClock },
  { name: "Anchor", icon: Anchor },
  { name: "Apple", icon: Apple },
  { name: "Archive", icon: Archive },
  { name: "Armchair", icon: Armchair },
  { name: "Award", icon: Award },
  { name: "Backpack", icon: Backpack },
  { name: "Banknote", icon: Banknote },
  { name: "BarChart3", icon: BarChart3 },
  { name: "Bed", icon: Bed },
  { name: "Bell", icon: Bell },
  { name: "Bike", icon: Bike },
  { name: "Binoculars", icon: Binoculars },
  { name: "Book", icon: Book },
  { name: "BookOpen", icon: BookOpen },
  { name: "Bot", icon: Bot },
  { name: "Box", icon: Box },
  { name: "Brain", icon: Brain },
  { name: "Briefcase", icon: Briefcase },
  { name: "Brush", icon: Brush },
  { name: "Building2", icon: Building2 },
  { name: "Cake", icon: Cake },
  { name: "Calculator", icon: Calculator },
  { name: "Calendar", icon: Calendar },
  { name: "Camera", icon: Camera },
  { name: "Car", icon: Car },
  { name: "Cat", icon: Cat },
  { name: "CheckSquare", icon: CheckSquare },
  { name: "Cherry", icon: Cherry },
  { name: "ClipboardList", icon: ClipboardList },
  { name: "Clock", icon: Clock },
  { name: "Cloud", icon: Cloud },
  { name: "Coffee", icon: Coffee },
  { name: "Compass", icon: Compass },
  { name: "Computer", icon: Computer },
  { name: "Cookie", icon: Cookie },
  { name: "Crown", icon: Crown },
  { name: "Database", icon: Database },
  { name: "Dog", icon: Dog },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "Egg", icon: Egg },
  { name: "Flame", icon: Flame },
  { name: "FlaskConical", icon: FlaskConical },
  { name: "Flower2", icon: Flower2 },
  { name: "ForkKnife", icon: ForkKnife },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Gem", icon: Gem },
  { name: "Gift", icon: Gift },
  { name: "Globe", icon: Globe },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "HandHeart", icon: HandHeart },
  { name: "Headphones", icon: Headphones },
  { name: "Heart", icon: Heart },
  { name: "HeartPulse", icon: HeartPulse },
  { name: "Home", icon: Home },
  { name: "IceCreamBowl", icon: IceCreamBowl },
  { name: "Laptop", icon: Laptop },
  { name: "Leaf", icon: Leaf },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "Lock", icon: Lock },
  { name: "Map", icon: Map },
  { name: "MapPin", icon: MapPin },
  { name: "Medal", icon: Medal },
  { name: "Megaphone", icon: Megaphone },
  { name: "MessageCircle", icon: MessageCircle },
  { name: "Mic", icon: Mic },
  { name: "Moon", icon: Moon },
  { name: "Mountain", icon: Mountain },
  { name: "Music", icon: Music },
  { name: "PaintBucket", icon: PaintBucket },
  { name: "Palette", icon: Palette },
  { name: "PartyPopper", icon: PartyPopper },
  { name: "PawPrint", icon: PawPrint },
  { name: "Pen", icon: Pen },
  { name: "PiggyBank", icon: PiggyBank },
  { name: "Plane", icon: Plane },
  { name: "Podcast", icon: Podcast },
  { name: "Puzzle", icon: Puzzle },
  { name: "Rocket", icon: Rocket },
  { name: "Sailboat", icon: Sailboat },
  { name: "Shield", icon: Shield },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "Skull", icon: Skull },
  { name: "Smartphone", icon: Smartphone },
  { name: "Smile", icon: Smile },
  { name: "Snowflake", icon: Snowflake },
  { name: "Star", icon: Star },
  { name: "Sun", icon: Sun },
  { name: "Sunrise", icon: Sunrise },
  { name: "Sunset", icon: Sunset },
  { name: "Sword", icon: Sword },
  { name: "Telescope", icon: Telescope },
  { name: "Tent", icon: Tent },
  { name: "Timer", icon: Timer },
  { name: "Trophy", icon: Trophy },
  { name: "Umbrella", icon: Umbrella },
  { name: "Utensils", icon: Utensils },
  { name: "Video", icon: Video },
  { name: "Watch", icon: Watch },
  { name: "Waves", icon: Waves },
  { name: "Weight", icon: Weight },
  { name: "Wheat", icon: Wheat },
  { name: "Wind", icon: Wind },
  { name: "Wine", icon: Wine },
  { name: "Wrench", icon: Wrench },
  { name: "Zap", icon: Zap },
];

export function getBoardIcon(iconName?: string): LucideIcon | null {
  if (!iconName) return null;
  const found = BOARD_ICONS.find((i) => i.name === iconName);
  return found?.icon ?? null;
}
