import type {
  FinanceAccount,
  TransactionCategory,
  Transaction,
  BudgetPlan,
  FinanceGoal,
  Loan,
  FinanceProject,
  EmergencyFund,
  ShoppingList,
} from "./finance-types";

const now = new Date();
const iso = (d: Date) => d.toISOString();
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
};

export const mockFinanceAccounts: FinanceAccount[] = [
  {
    id: "fin-acc-1",
    userId: "user-1",
    name: "Наличные",
    type: "cash",
    balance: 50000,
    currency: "RUB",
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
  {
    id: "fin-acc-2",
    userId: "user-1",
    name: "Карта Т-Банк",
    type: "card",
    balance: 120000,
    currency: "RUB",
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
  {
    id: "fin-acc-3",
    userId: "user-1",
    name: "Копилка",
    type: "savings",
    balance: 30000,
    currency: "RUB",
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
];

export const mockFinanceCategories: TransactionCategory[] = [
  // Продукты и питание
  {
    id: "cat-food",
    userId: "user-1",
    name: "Продукты",
    icon: "ShoppingCart",
    type: "expense",
    color: "emerald",
  },
  {
    id: "cat-delivery",
    userId: "user-1",
    name: "Доставка еды",
    icon: "Coffee",
    type: "expense",
    color: "emerald",
  },
  {
    id: "cat-restaurants",
    userId: "user-1",
    name: "Рестораны / Кафе",
    icon: "Utensils",
    type: "expense",
    color: "green",
  },
  // Дом и ЖКХ
  {
    id: "cat-rent",
    userId: "user-1",
    name: "Аренда жилья",
    icon: "Home",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-utilities",
    userId: "user-1",
    name: "Коммунальные платежи",
    icon: "ScrollText",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-electricity",
    userId: "user-1",
    name: "Электричество",
    icon: "Zap",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-water",
    userId: "user-1",
    name: "Вода / Отопление",
    icon: "Home",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-internet",
    userId: "user-1",
    name: "Интернет",
    icon: "Wifi",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-tv",
    userId: "user-1",
    name: "ТВ / Кабельное",
    icon: "Tv",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-repair",
    userId: "user-1",
    name: "Ремонт и быт",
    icon: "Wrench",
    type: "expense",
    color: "orange",
  },
  // Транспорт
  {
    id: "cat-car",
    userId: "user-1",
    name: "Автомобиль",
    icon: "Car",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-fuel",
    userId: "user-1",
    name: "Топливо",
    icon: "Fuel",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-car-parts",
    userId: "user-1",
    name: "Запчасти / Ремонт",
    icon: "Wrench",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-taxi",
    userId: "user-1",
    name: "Такси",
    icon: "Car",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-public-transport",
    userId: "user-1",
    name: "Общественный транспорт",
    icon: "Bus",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-train",
    userId: "user-1",
    name: "Поезд (билеты)",
    icon: "Train",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-plane",
    userId: "user-1",
    name: "Самолёт (билеты)",
    icon: "Plane",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-ship",
    userId: "user-1",
    name: "Корабль / Паром",
    icon: "Ship",
    type: "expense",
    color: "orange",
  },
  // Здоровье и спорт
  {
    id: "cat-doctor",
    userId: "user-1",
    name: "Врач / Клиника",
    icon: "Stethoscope",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-pharmacy",
    userId: "user-1",
    name: "Аптека / Таблетки",
    icon: "Pill",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-treatment",
    userId: "user-1",
    name: "Лечение",
    icon: "Heart",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-gym",
    userId: "user-1",
    name: "Спортзал / Фитнес",
    icon: "Dumbbell",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-vitamins",
    userId: "user-1",
    name: "Витамины",
    icon: "Pill",
    type: "expense",
    color: "green",
  },
  // Одежда и внешность
  {
    id: "cat-clothes",
    userId: "user-1",
    name: "Одежда",
    icon: "Shirt",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-shoes",
    userId: "user-1",
    name: "Обувь",
    icon: "Footprints",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-beauty",
    userId: "user-1",
    name: "Салон красоты",
    icon: "Sparkles",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-jewelry",
    userId: "user-1",
    name: "Украшения / Бижутерия",
    icon: "Gem",
    type: "expense",
    color: "purple",
  },
  {
    id: "cat-cosmetics",
    userId: "user-1",
    name: "Косметика",
    icon: "Sparkles",
    type: "expense",
    color: "pink",
  },
  // Развлечения и культура
  {
    id: "cat-cinema",
    userId: "user-1",
    name: "Кино",
    icon: "Film",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-video",
    userId: "user-1",
    name: "Видео / Подписки",
    icon: "Tv",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-music",
    userId: "user-1",
    name: "Музыка / Подписки",
    icon: "Music",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-theater",
    userId: "user-1",
    name: "Театр / Концерты",
    icon: "Drama",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-games",
    userId: "user-1",
    name: "Игры / Софт",
    icon: "Gamepad2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-tickets",
    userId: "user-1",
    name: "Билеты (мероприятия)",
    icon: "Ticket",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-books",
    userId: "user-1",
    name: "Книги",
    icon: "BookOpen",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-hobby",
    userId: "user-1",
    name: "Хобби",
    icon: "Heart",
    type: "expense",
    color: "rose",
  },
  // Образование
  {
    id: "cat-courses",
    userId: "user-1",
    name: "Курсы / Обучение",
    icon: "GraduationCap",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-books-edu",
    userId: "user-1",
    name: "Книги (учебные)",
    icon: "BookOpen",
    type: "expense",
    color: "indigo",
  },
  // Цифровые услуги и связь
  {
    id: "cat-mobile",
    userId: "user-1",
    name: "Мобильная связь",
    icon: "Smartphone",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-subscriptions",
    userId: "user-1",
    name: "Подписки (сервисы)",
    icon: "Radio",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-gadgets",
    userId: "user-1",
    name: "Техника / Гаджеты",
    icon: "ShoppingCart",
    type: "expense",
    color: "cyan",
  },
  // Личное и социальное
  {
    id: "cat-gifts",
    userId: "user-1",
    name: "Подарки",
    icon: "Gift",
    type: "expense",
    color: "teal",
  },
  {
    id: "cat-toys",
    userId: "user-1",
    name: "Игрушки / Детям",
    icon: "ToyBrick",
    type: "expense",
    color: "teal",
  },
  {
    id: "cat-children",
    userId: "user-1",
    name: "Дети (садик, школа, кружки)",
    icon: "Baby",
    type: "expense",
    color: "teal",
  },
  {
    id: "cat-pets",
    userId: "user-1",
    name: "Животные",
    icon: "Cat",
    type: "expense",
    color: "teal",
  },
  // Государственные расходы
  {
    id: "cat-taxes",
    userId: "user-1",
    name: "Налоги",
    icon: "Building2",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-fines",
    userId: "user-1",
    name: "Штрафы",
    icon: "AlertTriangle",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-fees",
    userId: "user-1",
    name: "Госпошлины",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-enforcement",
    userId: "user-1",
    name: "Исполнительное производство",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  // Кредиты и займы
  {
    id: "cat-mortgage",
    userId: "user-1",
    name: "Ипотека",
    icon: "Home",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-loan",
    userId: "user-1",
    name: "Потребительский кредит",
    icon: "Landmark",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-car-loan",
    userId: "user-1",
    name: "Автокредит",
    icon: "Car",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-microloan",
    userId: "user-1",
    name: "Займ",
    icon: "Banknote",
    type: "expense",
    color: "rose",
  },
  // Покупки и услуги
  {
    id: "cat-big-purchases",
    userId: "user-1",
    name: "Крупные покупки",
    icon: "Package",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-services",
    userId: "user-1",
    name: "Услуги",
    icon: "Hand",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-office",
    userId: "user-1",
    name: "Офис / Работа",
    icon: "Building2",
    type: "expense",
    color: "slate",
  },
  // Страховки
  {
    id: "cat-insurance",
    userId: "user-1",
    name: "Страхование",
    icon: "Shield",
    type: "expense",
    color: "lime",
  },
  // Прочее
  {
    id: "cat-other",
    userId: "user-1",
    name: "Прочие расходы",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Доходы
  {
    id: "cat-salary",
    userId: "user-1",
    name: "Зарплата",
    icon: "DollarSign",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-freelance",
    userId: "user-1",
    name: "Фриланс / Подработка",
    icon: "Wallet",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-deposit-interest",
    userId: "user-1",
    name: "Проценты по вкладам",
    icon: "PiggyBank",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-debt-return",
    userId: "user-1",
    name: "Возврат долгов",
    icon: "Banknote",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-bonus",
    userId: "user-1",
    name: "Бонусы / Достижения",
    icon: "Award",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-vip",
    userId: "user-1",
    name: "Премиум / VIP",
    icon: "Crown",
    type: "income",
    color: "emerald",
  },
  // Финансовые операции
  {
    id: "cat-savings",
    userId: "user-1",
    name: "Копилка / Накопления",
    icon: "PiggyBank",
    type: "income",
    color: "cyan",
  },
  {
    id: "cat-cash",
    userId: "user-1",
    name: "Кошелёк / Наличные",
    icon: "Wallet",
    type: "income",
    color: "cyan",
  },
  {
    id: "cat-bank-transfer",
    userId: "user-1",
    name: "Банк / Переводы между счетами",
    icon: "Landmark",
    type: "income",
    color: "cyan",
  },
];

export const mockFinanceTransactions: Transaction[] = [
  {
    id: "fin-tx-1",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-food",
    amount: 2500,
    description: "Продукты в Пятёрочке",
    tags: ["еда", "продукты"],
    date: daysAgo(1),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-2",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-taxi",
    amount: 1500,
    description: "Такси до офиса",
    tags: ["транспорт"],
    date: daysAgo(1),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-3",
    userId: "user-1",
    accountId: "fin-acc-1",
    type: "expense",
    categoryId: "cat-cinema",
    amount: 3500,
    description: "Кино с друзьями",
    tags: ["развлечения", "кино"],
    date: daysAgo(2),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-4",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "income",
    categoryId: "cat-salary",
    amount: 150000,
    description: "Зарплата за июнь",
    tags: ["зарплата"],
    date: daysAgo(3),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-5",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-rent",
    amount: 45000,
    description: "Аренда квартиры",
    tags: ["жильё", "аренда"],
    date: daysAgo(3),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-6",
    userId: "user-1",
    accountId: "fin-acc-1",
    type: "expense",
    categoryId: "cat-food",
    amount: 800,
    description: "Кофе и круассан",
    tags: ["еда", "кофе"],
    date: daysAgo(4),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-7",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-pharmacy",
    amount: 2200,
    description: "Аптека",
    tags: ["здоровье"],
    date: daysAgo(5),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-8",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-courses",
    amount: 5000,
    description: "Курс по TypeScript",
    tags: ["образование"],
    date: daysAgo(7),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-9",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-clothes",
    amount: 6000,
    description: "Новые кроссовки",
    tags: ["одежда", "обувь"],
    date: daysAgo(8),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-10",
    userId: "user-1",
    accountId: "fin-acc-3",
    type: "transfer",
    categoryId: "cat-savings",
    amount: 10000,
    description: "Перевод в копилку",
    tags: ["накопления"],
    date: daysAgo(10),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-11",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "income",
    categoryId: "cat-freelance",
    amount: 35000,
    description: "Фриланс — сайт для кафе",
    tags: ["фриланс", "разработка"],
    date: daysAgo(12),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-12",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-public-transport",
    amount: 3000,
    description: "Пополнение карты метро",
    tags: ["транспорт", "метро"],
    date: daysAgo(14),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-13",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-video",
    amount: 2000,
    description: "Подписка Spotify",
    tags: ["развлечения", "подписки"],
    date: daysAgo(15),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-14",
    userId: "user-1",
    accountId: "fin-acc-1",
    type: "expense",
    categoryId: "cat-services",
    amount: 1500,
    description: "Стрижка",
    tags: ["услуги"],
    date: daysAgo(20),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-15",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-delivery",
    amount: 4200,
    description: "Доставка суши",
    tags: ["еда", "доставка"],
    date: daysAgo(25),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
];

const currentMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
const currentMonthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0);

export const mockFinanceBudgetPlans: BudgetPlan[] = [
  {
    id: "fin-budget-1",
    userId: "user-1",
    period: "month",
    periodStart: currentMonthStart.toISOString().split("T")[0],
    periodEnd: currentMonthEnd.toISOString().split("T")[0],
    expectedIncome: 185000,
    categoryBudgets: [
      { categoryId: "cat-food", limit: 30000 },
      { categoryId: "cat-delivery", limit: 5000 },
      { categoryId: "cat-restaurants", limit: 10000 },
      { categoryId: "cat-rent", limit: 45000 },
      { categoryId: "cat-utilities", limit: 8000 },
      { categoryId: "cat-taxi", limit: 5000 },
      { categoryId: "cat-car", limit: 5000 },
      { categoryId: "cat-public-transport", limit: 3000 },
      { categoryId: "cat-pharmacy", limit: 5000 },
      { categoryId: "cat-gym", limit: 5000 },
      { categoryId: "cat-clothes", limit: 10000 },
      { categoryId: "cat-beauty", limit: 5000 },
      { categoryId: "cat-cinema", limit: 5000 },
      { categoryId: "cat-video", limit: 3000 },
      { categoryId: "cat-courses", limit: 10000 },
      { categoryId: "cat-mobile", limit: 2000 },
      { categoryId: "cat-gifts", limit: 5000 },
      { categoryId: "cat-mortgage", limit: 45000 },
      { categoryId: "cat-insurance", limit: 3000 },
      { categoryId: "cat-other", limit: 5000 },
    ],
    createdAt: iso(currentMonthStart),
    updatedAt: iso(currentMonthStart),
  },
];

const nextYear = new Date(now.getFullYear() + 1, 0, 1);

export const mockFinanceGoals: FinanceGoal[] = [
  {
    id: "fin-goal-1",
    userId: "user-1",
    name: "Новый ноутбук",
    targetAmount: 150000,
    currentAmount: 45000,
    deadline: nextYear.toISOString().split("T")[0],
    priority: "high",
    accountId: "fin-acc-3",
    autoDepositPercent: 10,
    completed: false,
    createdAt: iso(new Date("2025-03-01")),
    updatedAt: iso(now),
  },
  {
    id: "fin-goal-2",
    userId: "user-1",
    name: "Путешествие",
    targetAmount: 200000,
    currentAmount: 80000,
    deadline: nextYear.toISOString().split("T")[0],
    priority: "medium",
    accountId: "fin-acc-3",
    autoDepositPercent: 5,
    completed: false,
    createdAt: iso(new Date("2025-01-15")),
    updatedAt: iso(now),
  },
];

export const mockFinanceLoans: Loan[] = [
  {
    id: "fin-loan-1",
    userId: "user-1",
    name: "Ипотека",
    totalAmount: 5000000,
    interestRate: 8,
    monthlyPayment: 45000,
    remainingAmount: 4200000,
    nextPaymentDate: new Date(now.getFullYear(), now.getMonth() + 1, 10)
      .toISOString()
      .split("T")[0],
    repaymentType: "monthly",
    obligationType: "credit",
    overdueMonths: 0,
    createdAt: iso(new Date("2023-06-01")),
    updatedAt: iso(now),
  },
];

export const mockFinanceProjects: FinanceProject[] = [
  {
    id: "fin-proj-1",
    userId: "user-1",
    name: "Ремонт",
    icon: "PaintBucket",
    targetAmount: 300000,
    savedAmount: 50000,
    deadline: "2026-12-31",
    description: "Косметический ремонт квартиры",
    linkedCategoryIds: ["cat-rent"],
    color: "blue",
    completed: false,
    createdAt: iso(new Date("2025-06-01")),
    updatedAt: iso(now),
  },
  {
    id: "fin-proj-2",
    userId: "user-1",
    name: "Новый MacBook",
    icon: "Laptop",
    targetAmount: 250000,
    savedAmount: 100000,
    deadline: "2026-09-01",
    description: "MacBook Pro M4",
    linkedCategoryIds: ["cat-courses"],
    color: "purple",
    completed: false,
    createdAt: iso(new Date("2025-05-15")),
    updatedAt: iso(now),
  },
];

export const mockFinanceEmergencyFund: EmergencyFund = {
  id: "fin-emergency-1",
  userId: "user-1",
  targetAmount: 300000,
  currentAmount: 120000,
};

export const mockShoppingLists: ShoppingList[] = [
  {
    id: "shop-1",
    userId: "user-1",
    name: "Продукты на неделю",
    date: new Date().toISOString().split("T")[0],
    items: [
      { id: "item-1", name: "Молоко", quantity: 2, unit: "л", checked: false },
      {
        id: "item-2",
        name: "Хлеб",
        quantity: 1,
        unit: "шт",
        checked: true,
        amount: 60,
        accountId: "fin-acc-2",
        transactionId: "fin-tx-1",
      },
      { id: "item-3", name: "Яйца", quantity: 10, unit: "шт", checked: false },
      { id: "item-4", name: "Сыр", quantity: 200, unit: "г", checked: false },
      {
        id: "item-5",
        name: "Масло сливочное",
        quantity: 1,
        unit: "шт",
        checked: false,
      },
    ],
    completed: false,
    archived: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "shop-2",
    userId: "user-1",
    name: "Стройматериалы",
    date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    items: [
      {
        id: "item-6",
        name: "Шпаклёвка",
        quantity: 2,
        unit: "кг",
        checked: false,
      },
      {
        id: "item-7",
        name: "Краска белая",
        quantity: 1,
        unit: "л",
        checked: false,
      },
      { id: "item-8", name: "Валик", quantity: 2, unit: "шт", checked: false },
    ],
    completed: false,
    archived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
