export type CategoryGroupCategory = {
  id: string;
  name: string;
  icon: string;
  color: string;
  type: "expense" | "income";
};

export type CategoryGroup = {
  id: string;
  name: string;
  icon: string;
  accent: string;
  defaultColor: string;
  categories: CategoryGroupCategory[];
};

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    id: "expense",
    name: "Расходы",
    icon: "TrendingDown",
    accent: "#f43f5e",
    defaultColor: "rose",
    categories: [
      {
        id: "cat-other",
        name: "Прочие расходы",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-grocery",
        name: "Продукты",
        icon: "ShoppingCart",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-food-delivery",
        name: "Доставка еды",
        icon: "Bike",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-restaurant",
        name: "Ресторан",
        icon: "Utensils",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-coffee-shop",
        name: "Кофе",
        icon: "Coffee",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-cafe",
        name: "Кафе",
        icon: "Utensils",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-canteen",
        name: "Столовая",
        icon: "Soup",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-fastfood",
        name: "Фастфуд",
        icon: "Sandwich",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-vending",
        name: "Вендинг",
        icon: "ShoppingCart",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-confectionery",
        name: "Кондитерская",
        icon: "Cake",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-rent",
        name: "Аренда жилья",
        icon: "Home",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-utilities",
        name: "Коммуналка",
        icon: "ScrollText",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-electricity",
        name: "Электричество",
        icon: "Zap",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-cold-water",
        name: "Холодная вода",
        icon: "Droplets",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-hot-water",
        name: "Горячая вода",
        icon: "Flame",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-heating",
        name: "Отопление",
        icon: "Flame",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-gas",
        name: "Газ",
        icon: "Flame",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-trash",
        name: "Мусор",
        icon: "Trash2",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-major-repair",
        name: "Капремонт",
        icon: "Hammer",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-home-maintenance",
        name: "Ремонт",
        icon: "Wrench",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-furniture",
        name: "Мебель",
        icon: "Sofa",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-home-accessories",
        name: "Декор",
        icon: "Paintbrush",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-building-materials",
        name: "Стройматериалы",
        icon: "Hammer",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-appliances",
        name: "Техника",
        icon: "Tv",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-plant",
        name: "Растение",
        icon: "Flower2",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-internet",
        name: "Интернет",
        icon: "Wifi",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-mobile",
        name: "Мобильная связь",
        icon: "Smartphone",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-gasoline",
        name: "Бензин",
        icon: "Fuel",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-car-maintenance",
        name: "Обслуживание авто",
        icon: "Wrench",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-car-repair",
        name: "Ремонт авто",
        icon: "Car",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-parking",
        name: "Парковка",
        icon: "ParkingCircle",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-tolls",
        name: "Платные дороги",
        icon: "CreditCard",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-fines",
        name: "Штрафы",
        icon: "Gavel",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-taxi",
        name: "Такси",
        icon: "Car",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-public-transport",
        name: "Общественный транспорт",
        icon: "Bus",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-train",
        name: "Поезд",
        icon: "Train",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-flight",
        name: "Авиабилеты",
        icon: "Plane",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-scooter",
        name: "Самокат",
        icon: "Scooter",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-bicycle",
        name: "Велосипед",
        icon: "Bike",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-motorcycle",
        name: "Мотоцикл",
        icon: "Shield",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-train-ticket",
        name: "ЖД билеты",
        icon: "Train",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-bus-ticket",
        name: "Автобус",
        icon: "Bus",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-ship",
        name: "Корабль",
        icon: "Ship",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-movie",
        name: "Кино",
        icon: "Film",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-theater",
        name: "Театр",
        icon: "Drama",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-concert",
        name: "Концерт",
        icon: "Music",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-museum",
        name: "Музей",
        icon: "Landmark",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-exhibition",
        name: "Выставка",
        icon: "Paintbrush",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-sport-event",
        name: "Спортивное мероприятие",
        icon: "Dumbbell",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-gaming",
        name: "Игры",
        icon: "Gamepad2",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-subscription",
        name: "Подписка",
        icon: "Tv",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-books",
        name: "Книги",
        icon: "BookOpen",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-education",
        name: "Обучение",
        icon: "GraduationCap",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-courses",
        name: "Курсы",
        icon: "BookOpen",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-tutoring",
        name: "Репетитор",
        icon: "GraduationCap",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-stationery",
        name: "Канцелярия",
        icon: "ScrollText",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-doctor",
        name: "Врач",
        icon: "Stethoscope",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-pharmacy",
        name: "Аптека",
        icon: "Pill",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-hospital",
        name: "Больница",
        icon: "Heart",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-dental",
        name: "Стоматология",
        icon: "Stethoscope",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-analyses",
        name: "Анализы",
        icon: "Pill",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-optics",
        name: "Оптика",
        icon: "Eye",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-gym",
        name: "Спортзал",
        icon: "Dumbbell",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-sports",
        name: "Спорт",
        icon: "Dumbbell",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-clothing",
        name: "Одежда",
        icon: "Shirt",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-shoes",
        name: "Обувь",
        icon: "Footprints",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-accessories",
        name: "Аксессуары",
        icon: "Gem",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-cosmetics",
        name: "Косметика",
        icon: "Sparkles",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-perfume",
        name: "Парфюмерия",
        icon: "Sparkles",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-pet-food",
        name: "Корм для питомцев",
        icon: "Cat",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-vet",
        name: "Ветеринар",
        icon: "Heart",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-pet-accessories",
        name: "Аксессуары для питомцев",
        icon: "Cat",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-gifts",
        name: "Подарки",
        icon: "Gift",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-charity",
        name: "Благотворительность",
        icon: "Heart",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-entertainment",
        name: "Развлечения",
        icon: "Ticket",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-baby",
        name: "Ребёнок",
        icon: "Baby",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-toys",
        name: "Игрушки",
        icon: "ToyBrick",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-insurance",
        name: "Страховка",
        icon: "Shield",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-taxes",
        name: "Налоги",
        icon: "Receipt",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-fines2",
        name: "Штрафы и пени",
        icon: "Gavel",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-loan-payment",
        name: "Оплата кредита",
        icon: "Landmark",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-bank-fees",
        name: "Банковские комиссии",
        icon: "CreditCard",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-transfer",
        name: "Перевод",
        icon: "ArrowRightLeft",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "income",
    name: "Доходы",
    icon: "TrendingUp",
    accent: "#10b981",
    defaultColor: "emerald",
    categories: [
      {
        id: "cat-salary",
        name: "Зарплата",
        icon: "DollarSign",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-salary-official",
        name: "Оклад",
        icon: "DollarSign",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-advance",
        name: "Аванс",
        icon: "Wallet",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-bonus",
        name: "Премия",
        icon: "Award",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-fee",
        name: "Гонорар",
        icon: "Crown",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-commission",
        name: "Комиссионные",
        icon: "Percent",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-parttime",
        name: "Подработка",
        icon: "Briefcase",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-investment",
        name: "Инвестиционный доход",
        icon: "TrendingUp",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-deposit-interest",
        name: "Процент по вкладу",
        icon: "PiggyBank",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-royalty",
        name: "Роялти",
        icon: "Crown",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-exchange-rate",
        name: "Курсовая разница",
        icon: "TrendingUp",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-debt-return",
        name: "Возвращение долга",
        icon: "Banknote",
        color: "teal",
        type: "income",
      },
      {
        id: "cat-overpayment-return",
        name: "Возврат переплаты",
        icon: "RefreshCw",
        color: "teal",
        type: "income",
      },
      {
        id: "cat-debt-forgiveness",
        name: "Прощение долга",
        icon: "Heart",
        color: "teal",
        type: "income",
      },
      {
        id: "cat-tax-deduction",
        name: "Налоговый вычет",
        icon: "Receipt",
        color: "teal",
        type: "income",
      },
      {
        id: "cat-tax-recalculation",
        name: "Перерасчет налога",
        icon: "ScrollText",
        color: "teal",
        type: "income",
      },
      {
        id: "cat-scholarship",
        name: "Стипендия",
        icon: "GraduationCap",
        color: "indigo",
        type: "income",
      },
      {
        id: "cat-social-benefits",
        name: "Социальные пособия",
        icon: "Heart",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-subsidy",
        name: "Субсидия",
        icon: "Building2",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-maternity-capital",
        name: "Материнский капитал",
        icon: "Baby",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-insurance-payout",
        name: "Страховые выплаты",
        icon: "Shield",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-grant",
        name: "Гранты",
        icon: "Award",
        color: "indigo",
        type: "income",
      },
      {
        id: "cat-alimony",
        name: "Алименты",
        icon: "Heart",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-compensation",
        name: "Компенсация",
        icon: "Hand",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-rental",
        name: "Аренда",
        icon: "Key",
        color: "blue",
        type: "income",
      },
      {
        id: "cat-property-sale",
        name: "Продажа имущества",
        icon: "Building2",
        color: "blue",
        type: "income",
      },
      {
        id: "cat-item-sale",
        name: "Продажа вещи",
        icon: "Package",
        color: "blue",
        type: "income",
      },
      {
        id: "cat-loan-received",
        name: "Получение кредита/займа",
        icon: "Landmark",
        color: "cyan",
        type: "income",
      },
      {
        id: "cat-gift",
        name: "Подарок",
        icon: "Gift",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-winnings",
        name: "Выигрыши",
        icon: "Gem",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-inheritance",
        name: "Наследство",
        icon: "Heart",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-treasure",
        name: "Клад",
        icon: "Gem",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-finding",
        name: "Находка",
        icon: "Search",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-cashback",
        name: "Кэшбэк",
        icon: "RefreshCw",
        color: "amber",
        type: "income",
      },
    ],
  },
];

export const getCategoryGroup = (
  catName: string,
  catType?: string,
): CategoryGroup => {
  const targetId = catType === "income" ? "income" : "expense";
  return (
    CATEGORY_GROUPS.find((g) => g.id === targetId) ??
    CATEGORY_GROUPS[0]
  );
};
