export type CategoryGroupCategory = {
  id: string;
  name: string;
  icon: string;
  color: string;
  type: "expense" | "income";
};

export type CategoryGroup = {
  id: string;
  name: string;
  icon: string;
  accent: string;
  defaultColor: string;
  categories: CategoryGroupCategory[];
};

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    id: "food",
    name: "Продукты и питание",
    icon: "ShoppingCart",
    accent: "#10b981",
    defaultColor: "emerald",
    categories: [
      {
        id: "cat-grocery",
        name: "Магазин",
        icon: "ShoppingCart",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-food-delivery",
        name: "Доставка продуктов",
        icon: "ShoppingCart",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-meal-delivery",
        name: "Доставка готовой еды",
        icon: "Utensils",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-coffee-shop",
        name: "Кофейня",
        icon: "Coffee",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-cafe",
        name: "Кафе",
        icon: "Coffee",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-canteen",
        name: "Столовая",
        icon: "Soup",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-restaurant",
        name: "Ресторан",
        icon: "Utensils",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-fastfood",
        name: "Фастфуд",
        icon: "Sandwich",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-vending",
        name: "Вендинг",
        icon: "Coffee",
        color: "emerald",
        type: "expense",
      },
      {
        id: "cat-confectionery",
        name: "Кондитерская",
        icon: "Cake",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-food-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "home",
    name: "Дом",
    icon: "Home",
    accent: "#3b82f6",
    defaultColor: "blue",
    categories: [
      {
        id: "cat-rent",
        name: "Аренда",
        icon: "Home",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-utilities",
        name: "ЖКУ",
        icon: "ScrollText",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-electricity",
        name: "Электроэнергия",
        icon: "Zap",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-cold-water",
        name: "Водоснабжение (холодная вода)",
        icon: "Droplets",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-hot-water",
        name: "Горячая вода",
        icon: "Droplets",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-heating",
        name: "Отопление / Тепло",
        icon: "Flame",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-gas",
        name: "Газ",
        icon: "Flame",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-trash",
        name: "Вывоз мусора / ТКО",
        icon: "Trash2",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-major-repair",
        name: "Капитальный ремонт (взносы в фонд)",
        icon: "Wrench",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-home-maintenance",
        name: "Содержание и ремонт жилья",
        icon: "Wrench",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-common-areas",
        name: "Общедомовые нужды",
        icon: "ScrollText",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-heated-floor",
        name: "Теплый пол",
        icon: "Flame",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-cleaning",
        name: "Бытовая химия",
        icon: "Sparkles",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-furniture",
        name: "Мебель",
        icon: "Sofa",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-home-accessories",
        name: "Аксессуары",
        icon: "Gem",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-building-materials",
        name: "Стройматериалы",
        icon: "Hammer",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-appliances",
        name: "Бытовая техника",
        icon: "Zap",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-plant",
        name: "Растение",
        icon: "Flower2",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-home-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "connectivity",
    name: "Связь и информационные услуги",
    icon: "Smartphone",
    accent: "#06b6d4",
    defaultColor: "cyan",
    categories: [
      {
        id: "cat-internet",
        name: "Интернет",
        icon: "Wifi",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-mobile",
        name: "Мобильная связь",
        icon: "Smartphone",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-cable-tv",
        name: "Кабельное / Цифровое ТВ",
        icon: "Tv",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-antenna",
        name: "Антенна",
        icon: "Radio",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-subscriptions",
        name: "Подписки",
        icon: "Radio",
        color: "purple",
        type: "expense",
      },
      {
        id: "cat-intercom",
        name: "Домофон (абонентская плата)",
        icon: "Smartphone",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-phone",
        name: "Телефон (абонентская плата)",
        icon: "Smartphone",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-alarm",
        name: "Охранная сигнализация (мониторинг)",
        icon: "Lock",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-cloud",
        name: "Облачные хранилища",
        icon: "Cloud",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-vpn",
        name: "VPN",
        icon: "Lock",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-servers",
        name: "Серверы",
        icon: "Monitor",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-connectivity-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "transport",
    name: "Транспорт",
    icon: "Car",
    accent: "#f97316",
    defaultColor: "orange",
    categories: [
      {
        id: "cat-transit-pass",
        name: "Проездной",
        icon: "Bus",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-car",
        name: "Авто",
        icon: "Car",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-bicycle",
        name: "Велосипед",
        icon: "Bike",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-scooter",
        name: "Самокат",
        icon: "Scooter",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-kicksharing",
        name: "Кикшеринг",
        icon: "Scooter",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-carsharing",
        name: "Каршеринг",
        icon: "Car",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-motorcycle",
        name: "Мотоцикл",
        icon: "Shield",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-train",
        name: "Поезд/электричка",
        icon: "Train",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-metro",
        name: "Метро",
        icon: "Train",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-tram",
        name: "Трамвай",
        icon: "Train",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-trolleybus",
        name: "Троллейбус",
        icon: "Bus",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-taxi",
        name: "Такси",
        icon: "Car",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-plane",
        name: "Самолет",
        icon: "Plane",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-ship",
        name: "Корабль",
        icon: "Ship",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-fuel",
        name: "Топливо",
        icon: "Fuel",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-parking",
        name: "Платные парковки",
        icon: "ParkingCircle",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-traffic-fines",
        name: "Штрафы ГИБДД",
        icon: "Gavel",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-tolls",
        name: "Платные дороги",
        icon: "Car",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-car-wash",
        name: "Мойка",
        icon: "Droplets",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-car-service",
        name: "ТО",
        icon: "Wrench",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-car-repair",
        name: "Ремонт",
        icon: "Wrench",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-car-insurance",
        name: "Страховка",
        icon: "Shield",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-transport-tax",
        name: "Транспортный налог",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-tow-truck",
        name: "Эвакуатор",
        icon: "Car",
        color: "orange",
        type: "expense",
      },
      {
        id: "cat-transport-accessories",
        name: "Аксессуары",
        icon: "Gem",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-transport-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "health",
    name: "Медицина и здоровье",
    icon: "Heart",
    accent: "#ec4899",
    defaultColor: "pink",
    categories: [
      {
        id: "cat-doctor",
        name: "Врач (прием, консультация)",
        icon: "Stethoscope",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-medication",
        name: "Таблетки (лекарства, витамины, БАДы)",
        icon: "Pill",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-gym",
        name: "Спортзал (абонемент, разовые посещения)",
        icon: "Dumbbell",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-lab-tests",
        name: "Анализы",
        icon: "Pill",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-pharmacy",
        name: "Аптека",
        icon: "Pill",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-massage",
        name: "Массаж",
        icon: "Heart",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-physiotherapy",
        name: "Физиотерапия",
        icon: "Heart",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-rehab",
        name: "Реабилитация / ЛФК",
        icon: "Heart",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-swimming-pool",
        name: "Бассейн (абонемент или разовое посещение)",
        icon: "Droplets",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-vaccination",
        name: "Вакцинация",
        icon: "Syringe",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-day-hospital",
        name: "Дневной стационар",
        icon: "Stethoscope",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-home-doctor",
        name: "Домашний вызов врача",
        icon: "Stethoscope",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-ambulance",
        name: "Скорая помощь",
        icon: "Heart",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-sanatorium",
        name: "Санаторий / Профилакторий",
        icon: "Heart",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-vitamins",
        name: "Витаминно-минеральные комплексы",
        icon: "Pill",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-procedures",
        name: "Процедуры",
        icon: "Stethoscope",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-health-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "clothing",
    name: "Одежда и аксессуары",
    icon: "Shirt",
    accent: "#8b5cf6",
    defaultColor: "violet",
    categories: [
      {
        id: "cat-clothes",
        name: "Одежда",
        icon: "Shirt",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-shoes",
        name: "Обувь",
        icon: "Footprints",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-jewelry",
        name: "Украшения",
        icon: "Gem",
        color: "purple",
        type: "expense",
      },
      {
        id: "cat-bags",
        name: "Сумки",
        icon: "Luggage",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-backpacks",
        name: "Рюкзаки",
        icon: "Backpack",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-luggage",
        name: "Чемоданы / Дорожные сумки",
        icon: "Luggage",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-belts",
        name: "Ремни",
        icon: "Shirt",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-ties",
        name: "Галстуки / Бабочки",
        icon: "Shirt",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-scarves",
        name: "Шарфы / Платки",
        icon: "Shirt",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-gloves",
        name: "Перчатки / Варежки",
        icon: "Shirt",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-hats",
        name: "Шапки / Кепки / Панамы",
        icon: "Shirt",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-socks",
        name: "Носки / Колготки / Чулки",
        icon: "Footprints",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-underwear",
        name: "Нижнее белье",
        icon: "Shirt",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-swimwear",
        name: "Купальники / Плавки",
        icon: "Shirt",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-sportswear",
        name: "Спортивная форма",
        icon: "Shirt",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-pajamas",
        name: "Пижамы / Домашняя одежда",
        icon: "Shirt",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-robes",
        name: "Халаты",
        icon: "Shirt",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-kids-clothes",
        name: "Детская одежда",
        icon: "Baby",
        color: "teal",
        type: "expense",
      },
      {
        id: "cat-hair-accessories",
        name: "Аксессуары для волос",
        icon: "Sparkles",
        color: "pink",
        type: "expense",
      },
      {
        id: "cat-sunglasses",
        name: "Очки солнцезащитные",
        icon: "Glasses",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-umbrellas",
        name: "Зонты",
        icon: "Umbrella",
        color: "blue",
        type: "expense",
      },
      {
        id: "cat-costume-jewelry",
        name: "Бижутерия",
        icon: "Gem",
        color: "purple",
        type: "expense",
      },
      {
        id: "cat-wallets",
        name: "Кошельки / Портмоне",
        icon: "Wallet",
        color: "violet",
        type: "expense",
      },
      {
        id: "cat-clothing-repair",
        name: "Ремонт одежды / обуви (химчистка, мастерская)",
        icon: "Wrench",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-clothing-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "education",
    name: "Образование",
    icon: "GraduationCap",
    accent: "#6366f1",
    defaultColor: "indigo",
    categories: [
      {
        id: "cat-training",
        name: "Обучение",
        icon: "GraduationCap",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-books",
        name: "Книги",
        icon: "BookOpen",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-textbooks",
        name: "Учебники / Учебные пособия",
        icon: "BookOpen",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-stationery",
        name: "Тетради / Блокноты / Письменные принадлежности",
        icon: "Pen",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-edu-subscriptions",
        name: "Подписка на образовательные платформы",
        icon: "Radio",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-tutor",
        name: "Репетитор / Преподаватель",
        icon: "GraduationCap",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-language-courses",
        name: "Языковые курсы",
        icon: "BookOpen",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-online-school",
        name: "Онлайн-школы / Академии",
        icon: "Monitor",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-university",
        name: "Вуз / Колледж",
        icon: "School",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-school",
        name: "Школа (частная / платные услуги)",
        icon: "School",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-kindergarten",
        name: "Детский сад (платный / частный)",
        icon: "Baby",
        color: "teal",
        type: "expense",
      },
      {
        id: "cat-clubs",
        name: "Кружки / Секции (музыка, спорт, рисование, танцы)",
        icon: "Music",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-exams",
        name: "Экзамены / Тестирование (оплата за сдачу, сертификация)",
        icon: "ScrollText",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-certificates",
        name: "Дипломы / Сертификаты / Свидетельства",
        icon: "ScrollText",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-enrollment-fees",
        name: "Вступительные взносы",
        icon: "Banknote",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-library",
        name: "Библиотека (платный абонемент, штрафы)",
        icon: "BookOpen",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-office-supplies",
        name: "Канцелярия (бумага, папки, файлы, степлеры, скрепки)",
        icon: "Pen",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-printing",
        name: "Печать / Копирование / Брошюровка",
        icon: "Pen",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-flash-drives",
        name: "Портативные накопители (флешки, внешние диски для учебы)",
        icon: "Package",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-edu-apps",
        name: "Образовательные приложения (платные)",
        icon: "Smartphone",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-marathons",
        name: "Марафоны / Интенсивы (образовательные)",
        icon: "GraduationCap",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-conferences",
        name: "Конференции / Семинары (оплата участия)",
        icon: "Ticket",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-driving-school",
        name: "Вождение (автошкола, инструктор)",
        icon: "Car",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-mentor",
        name: "Тьютор / Наставник",
        icon: "GraduationCap",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-after-school",
        name: "Продленка",
        icon: "Baby",
        color: "teal",
        type: "expense",
      },
      {
        id: "cat-edu-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "entertainment",
    name: "Развлечения",
    icon: "Film",
    accent: "#f59e0b",
    defaultColor: "amber",
    categories: [
      {
        id: "cat-cinema",
        name: "Кино",
        icon: "Film",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-music",
        name: "Музыка",
        icon: "Music",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-games",
        name: "Игры",
        icon: "Gamepad2",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-tickets",
        name: "Билеты",
        icon: "Ticket",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-theater",
        name: "Театр",
        icon: "Drama",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-concerts",
        name: "Концерты",
        icon: "Music",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-quests",
        name: "Квесты",
        icon: "Puzzle",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-amusement-rides",
        name: "Аттракционы",
        icon: "ParkingCircle",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-amusement-park",
        name: "Парки развлечений",
        icon: "PartyPopper",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-zoo",
        name: "Зоопарк",
        icon: "Cat",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-aquarium",
        name: "Океанариум",
        icon: "Ship",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-dolphinarium",
        name: "Дельфинарий",
        icon: "Ship",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-museum",
        name: "Музеи",
        icon: "Building2",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-exhibitions",
        name: "Выставки",
        icon: "Building2",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-circus",
        name: "Цирк",
        icon: "Drama",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-bowling",
        name: "Боулинг",
        icon: "Gamepad2",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-billiards",
        name: "Бильярд",
        icon: "Gamepad2",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-ice-rink",
        name: "Каток",
        icon: "Snowflake",
        color: "cyan",
        type: "expense",
      },
      {
        id: "cat-laser-tag",
        name: "Лазертаг",
        icon: "Target",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-paintball",
        name: "Пейнтбол",
        icon: "Target",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-water-park",
        name: "Аквапарк",
        icon: "Droplets",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-nightclubs",
        name: "Ночные клубы",
        icon: "Music",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-bars",
        name: "Бары",
        icon: "Coffee",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-casino",
        name: "Казино",
        icon: "Dices",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-slot-machines",
        name: "Игровые автоматы",
        icon: "Gamepad2",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-holidays",
        name: "Праздники",
        icon: "PartyPopper",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-fireworks",
        name: "Фейерверки",
        icon: "Sparkles",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-photoshoot",
        name: "Фотосессии",
        icon: "Camera",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-streaming",
        name: "Подписки",
        icon: "Radio",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-video-games",
        name: "Видеоигры",
        icon: "Gamepad2",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-consoles",
        name: "Игровые консоли",
        icon: "Gamepad2",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-gaming-accessories",
        name: "Аксессуары для игр",
        icon: "Gamepad2",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-board-games",
        name: "Настольные игры",
        icon: "Dices",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-puzzles",
        name: "Пазлы",
        icon: "Puzzle",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-building-toys",
        name: "Конструкторы",
        icon: "ToyBrick",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-fiction",
        name: "Художественные книги",
        icon: "BookOpen",
        color: "indigo",
        type: "expense",
      },
      {
        id: "cat-photo-printing",
        name: "Печать фотографий",
        icon: "Camera",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-festivals",
        name: "Фестивали",
        icon: "Music",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-fairs",
        name: "Ярмарки",
        icon: "ShoppingCart",
        color: "amber",
        type: "expense",
      },
      {
        id: "cat-entertainment-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "government",
    name: "Госуслуги",
    icon: "Building2",
    accent: "#ef4444",
    defaultColor: "red",
    categories: [
      {
        id: "cat-documents",
        name: "Документы",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-fines",
        name: "Штрафы",
        icon: "AlertTriangle",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-taxes",
        name: "Налоги",
        icon: "Building2",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-fees",
        name: "Пошлины",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-licenses",
        name: "Лицензии",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-permits",
        name: "Разрешения",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-government-certificates",
        name: "Справки",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-international-passport",
        name: "Загранпаспорт",
        icon: "Globe",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-domestic-passport",
        name: "Внутренний паспорт",
        icon: "Globe",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-drivers-license",
        name: "Водительские права",
        icon: "Car",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-car-registration",
        name: "Регистрация автомобиля",
        icon: "Car",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-residence-registration",
        name: "Регистрация по месту жительства",
        icon: "Home",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-courts",
        name: "Суды",
        icon: "Gavel",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-enforcement-fees",
        name: "Исполнительные сборы",
        icon: "AlertTriangle",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-notary",
        name: "Нотариус",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-powers-of-attorney",
        name: "Доверенности",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-certified-copies",
        name: "Заверение копий",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-apostille",
        name: "Апостиль",
        icon: "Globe",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-document-translation",
        name: "Перевод документов",
        icon: "Globe",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-consular-fee",
        name: "Консульский сбор",
        icon: "Globe",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-visa",
        name: "Виза",
        icon: "Globe",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-certification",
        name: "Сертификация",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-meter-verification",
        name: "Поверка счетчиков",
        icon: "Zap",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-privatization",
        name: "Приватизация",
        icon: "Home",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-inheritance-processing",
        name: "Оформление наследства",
        icon: "Heart",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-deed-of-gift",
        name: "Дарственная",
        icon: "Gift",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-property-registration",
        name: "Купля-продажа недвижимости (регистрация)",
        icon: "Home",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-egrn-extracts",
        name: "Выписки из ЕГРН",
        icon: "ScrollText",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-cadastral-work",
        name: "Кадастровые работы",
        icon: "Home",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-property-appraisal",
        name: "Оценка имущества",
        icon: "Building2",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-state-expertise",
        name: "Госэкспертиза",
        icon: "Building2",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-excise-duties",
        name: "Акцизы",
        icon: "Building2",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-customs",
        name: "Таможенные платежи",
        icon: "Globe",
        color: "red",
        type: "expense",
      },
      {
        id: "cat-government-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "extra",
    name: "Дополнительно",
    icon: "ShoppingCart",
    accent: "#6b7280",
    defaultColor: "slate",
    categories: [
      {
        id: "cat-service",
        name: "Услуга",
        icon: "Hand",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-purchase",
        name: "Покупка",
        icon: "ShoppingCart",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-rental-extra",
        name: "Аренда",
        icon: "Key",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "loans",
    name: "Кредиты",
    icon: "Landmark",
    accent: "#f43f5e",
    defaultColor: "rose",
    categories: [
      {
        id: "cat-loans",
        name: "Займы",
        icon: "Banknote",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-mortgage",
        name: "Ипотека",
        icon: "Home",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-car-loan",
        name: "Автокредит",
        icon: "Car",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-consumer-loan",
        name: "Потребительский кредит",
        icon: "Landmark",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-credit-card-debt",
        name: "Кредитная карта (погашение долга)",
        icon: "CreditCard",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-microloans",
        name: "Микрозаймы",
        icon: "Banknote",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-refinancing",
        name: "Рефинансирование",
        icon: "RefreshCw",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-loan-interest",
        name: "Проценты по кредиту",
        icon: "Percent",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-loan-issuance-fee",
        name: "Комиссия за выдачу кредита",
        icon: "Percent",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-loan-penalties",
        name: "Штрафы по кредиту (пеня, неустойка)",
        icon: "AlertTriangle",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-loan-insurance",
        name: "Страховка кредита (если включена в платеж)",
        icon: "Shield",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-annuity",
        name: "Аннуитетный платеж",
        icon: "Landmark",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-differentiated",
        name: "Дифференцированный платеж",
        icon: "Landmark",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-early-repayment",
        name: "Досрочное погашение",
        icon: "Check",
        color: "green",
        type: "expense",
      },
      {
        id: "cat-loan-holidays",
        name: "Продление кредита / Каникулы",
        icon: "Calendar",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-overpayment",
        name: "Переплата по кредиту",
        icon: "Percent",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-debt-obligations",
        name: "Долговые обязательства (расписки, векселя)",
        icon: "ScrollText",
        color: "rose",
        type: "expense",
      },
      {
        id: "cat-loans-other",
        name: "Иное",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "purchases",
    name: "Покупки и услуги",
    icon: "ShoppingCart",
    accent: "#6b7280",
    defaultColor: "slate",
    categories: [
      {
        id: "cat-big-purchases",
        name: "Крупные покупки",
        icon: "Package",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-services",
        name: "Услуги",
        icon: "Hand",
        color: "slate",
        type: "expense",
      },
      {
        id: "cat-office",
        name: "Офис / Работа",
        icon: "Building2",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "insurance",
    name: "Страховки",
    icon: "Shield",
    accent: "#84cc16",
    defaultColor: "lime",
    categories: [
      {
        id: "cat-insurance",
        name: "Страхование",
        icon: "Shield",
        color: "lime",
        type: "expense",
      },
    ],
  },
  {
    id: "other",
    name: "Прочее",
    icon: "MoreHorizontal",
    accent: "#9ca3af",
    defaultColor: "slate",
    categories: [
      {
        id: "cat-other",
        name: "Прочие расходы",
        icon: "MoreHorizontal",
        color: "slate",
        type: "expense",
      },
    ],
  },
  {
    id: "salary-work",
    name: "Зарплата и работа",
    icon: "DollarSign",
    accent: "#10b981",
    defaultColor: "emerald",
    categories: [
      {
        id: "cat-salary",
        name: "Зарплата",
        icon: "DollarSign",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-salary-official",
        name: "Оклад",
        icon: "DollarSign",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-advance",
        name: "Аванс",
        icon: "Wallet",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-bonus",
        name: "Премия",
        icon: "Award",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-fee",
        name: "Гонорар",
        icon: "Crown",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-commission",
        name: "Комиссионные",
        icon: "Percent",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-parttime",
        name: "Подработка",
        icon: "Briefcase",
        color: "emerald",
        type: "income",
      },
    ],
  },
  {
    id: "investment-income",
    name: "Инвестиционные доходы",
    icon: "TrendingUp",
    accent: "#10b981",
    defaultColor: "emerald",
    categories: [
      {
        id: "cat-investment",
        name: "Инвестиционный доход",
        icon: "TrendingUp",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-deposit-interest",
        name: "Процент по банковскому вкладу",
        icon: "PiggyBank",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-royalty",
        name: "Роялти",
        icon: "Crown",
        color: "emerald",
        type: "income",
      },
      {
        id: "cat-exchange-rate",
        name: "Курсовая разница",
        icon: "TrendingUp",
        color: "emerald",
        type: "income",
      },
    ],
  },
  {
    id: "debt-returns",
    name: "Возвраты и долги",
    icon: "Banknote",
    accent: "#14b8a6",
    defaultColor: "teal",
    categories: [
      {
        id: "cat-debt-return",
        name: "Возвращение долга",
        icon: "Banknote",
        color: "teal",
        type: "income",
      },
      {
        id: "cat-overpayment-return",
        name: "Возврат переплаты",
        icon: "RefreshCw",
        color: "teal",
        type: "income",
      },
      {
        id: "cat-debt-forgiveness",
        name: "Прощение долга",
        icon: "Heart",
        color: "teal",
        type: "income",
      },
      {
        id: "cat-tax-deduction",
        name: "Налоговый вычет",
        icon: "Receipt",
        color: "teal",
        type: "income",
      },
      {
        id: "cat-tax-recalculation",
        name: "Перерасчет налога",
        icon: "ScrollText",
        color: "teal",
        type: "income",
      },
    ],
  },
  {
    id: "social-benefits",
    name: "Пособия и компенсации",
    icon: "Heart",
    accent: "#ec4899",
    defaultColor: "pink",
    categories: [
      {
        id: "cat-scholarship",
        name: "Стипендия",
        icon: "GraduationCap",
        color: "indigo",
        type: "income",
      },
      {
        id: "cat-social-benefits",
        name: "Социальные пособия",
        icon: "Heart",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-subsidy",
        name: "Субсидия",
        icon: "Building2",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-maternity-capital",
        name: "Материнский капитал",
        icon: "Baby",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-insurance-payout",
        name: "Страховые выплаты",
        icon: "Shield",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-grant",
        name: "Гранты",
        icon: "Award",
        color: "indigo",
        type: "income",
      },
      {
        id: "cat-alimony",
        name: "Алименты",
        icon: "Heart",
        color: "pink",
        type: "income",
      },
      {
        id: "cat-compensation",
        name: "Компенсация",
        icon: "Hand",
        color: "pink",
        type: "income",
      },
    ],
  },
  {
    id: "property-income",
    name: "Доходы от имущества",
    icon: "Key",
    accent: "#3b82f6",
    defaultColor: "blue",
    categories: [
      {
        id: "cat-rental",
        name: "Аренда",
        icon: "Key",
        color: "blue",
        type: "income",
      },
      {
        id: "cat-property-sale",
        name: "Продажа имущества",
        icon: "Building2",
        color: "blue",
        type: "income",
      },
      {
        id: "cat-item-sale",
        name: "Продажа вещи",
        icon: "Package",
        color: "blue",
        type: "income",
      },
    ],
  },
  {
    id: "credit-loans",
    name: "Кредиты и займы",
    icon: "Landmark",
    accent: "#06b6d4",
    defaultColor: "cyan",
    categories: [
      {
        id: "cat-loan-received",
        name: "Получение кредита/займа",
        icon: "Landmark",
        color: "cyan",
        type: "income",
      },
    ],
  },
  {
    id: "other-income",
    name: "Прочие доходы",
    icon: "Gift",
    accent: "#f59e0b",
    defaultColor: "amber",
    categories: [
      {
        id: "cat-gift",
        name: "Подарок",
        icon: "Gift",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-winnings",
        name: "Выигрыши",
        icon: "Gem",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-inheritance",
        name: "Наследство",
        icon: "Heart",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-treasure",
        name: "Клад",
        icon: "Gem",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-finding",
        name: "Находка",
        icon: "Search",
        color: "amber",
        type: "income",
      },
      {
        id: "cat-cashback",
        name: "Кэшбэк",
        icon: "RefreshCw",
        color: "amber",
        type: "income",
      },
    ],
  },
];

export const getCategoryGroup = (catName: string, catType?: string): CategoryGroup => {
  for (const group of CATEGORY_GROUPS) {
    for (const c of group.categories) {
      if (c.name === catName) return group;
    }
  }
  const fallbackId = catType === "income" ? "other-income" : "other";
  return (
    CATEGORY_GROUPS.find((g) => g.id === fallbackId) ??
    CATEGORY_GROUPS[CATEGORY_GROUPS.length - 1]
  );
};
