import type {
  FinanceAccount,
  TransactionCategory,
  Transaction,
  BudgetPlan,
  FinanceGoal,
  Loan,
  FinanceProject,
  EmergencyFund,
} from "./finance-types";

const now = new Date();
const iso = (d: Date) => d.toISOString();
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
};

export const mockFinanceAccounts: FinanceAccount[] = [
  {
    id: "fin-acc-1",
    userId: "user-1",
    name: "Наличные",
    type: "cash",
    balance: 50000,
    currency: "RUB",
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
  {
    id: "fin-acc-2",
    userId: "user-1",
    name: "Карта Т-Банк",
    type: "card",
    balance: 120000,
    currency: "RUB",
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
  {
    id: "fin-acc-3",
    userId: "user-1",
    name: "Копилка",
    type: "savings",
    balance: 30000,
    currency: "RUB",
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
];

export const mockFinanceCategories: TransactionCategory[] = [
  {
    id: "fin-cat-1",
    userId: "user-1",
    name: "Еда",
    icon: "utensils",
    type: "expense",
    color: "#ef4444",
  },
  {
    id: "fin-cat-2",
    userId: "user-1",
    name: "Транспорт",
    icon: "car",
    type: "expense",
    color: "#f97316",
  },
  {
    id: "fin-cat-3",
    userId: "user-1",
    name: "Жильё",
    icon: "home",
    type: "expense",
    color: "#eab308",
  },
  {
    id: "fin-cat-4",
    userId: "user-1",
    name: "Одежда",
    icon: "shirt",
    type: "expense",
    color: "#22c55e",
  },
  {
    id: "fin-cat-5",
    userId: "user-1",
    name: "Развлечения",
    icon: "gamepad",
    type: "expense",
    color: "#3b82f6",
  },
  {
    id: "fin-cat-6",
    userId: "user-1",
    name: "Здоровье",
    icon: "heart",
    type: "expense",
    color: "#ec4899",
  },
  {
    id: "fin-cat-7",
    userId: "user-1",
    name: "Образование",
    icon: "book",
    type: "expense",
    color: "#8b5cf6",
  },
  {
    id: "fin-cat-8",
    userId: "user-1",
    name: "Прочее",
    icon: "ellipsis",
    type: "expense",
    color: "#6b7280",
  },
  {
    id: "fin-cat-9",
    userId: "user-1",
    name: "Зарплата",
    icon: "briefcase",
    type: "income",
    color: "#10b981",
  },
  {
    id: "fin-cat-10",
    userId: "user-1",
    name: "Фриланс",
    icon: "laptop",
    type: "income",
    color: "#06b6d4",
  },
];

export const mockFinanceTransactions: Transaction[] = [
  {
    id: "fin-tx-1",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "fin-cat-1",
    amount: 2500,
    description: "Продукты в Пятёрочке",
    tags: ["еда", "продукты"],
    date: daysAgo(1),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-2",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "fin-cat-2",
    amount: 1500,
    description: "Такси до офиса",
    tags: ["транспорт"],
    date: daysAgo(1),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-3",
    userId: "user-1",
    accountId: "fin-acc-1",
    type: "expense",
    categoryId: "fin-cat-5",
    amount: 3500,
    description: "Кино с друзьями",
    tags: ["развлечения", "кино"],
    date: daysAgo(2),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-4",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "income",
    categoryId: "fin-cat-9",
    amount: 150000,
    description: "Зарплата за июнь",
    tags: ["зарплата"],
    date: daysAgo(3),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-5",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "fin-cat-3",
    amount: 45000,
    description: "Аренда квартиры",
    tags: ["жильё", "аренда"],
    date: daysAgo(3),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-6",
    userId: "user-1",
    accountId: "fin-acc-1",
    type: "expense",
    categoryId: "fin-cat-1",
    amount: 800,
    description: "Кофе и круассан",
    tags: ["еда", "кофе"],
    date: daysAgo(4),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-7",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "fin-cat-6",
    amount: 2200,
    description: "Аптека",
    tags: ["здоровье"],
    date: daysAgo(5),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-8",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "fin-cat-7",
    amount: 5000,
    description: "Курс по TypeScript",
    tags: ["образование"],
    date: daysAgo(7),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-9",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "fin-cat-4",
    amount: 6000,
    description: "Новые кроссовки",
    tags: ["одежда", "обувь"],
    date: daysAgo(8),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-10",
    userId: "user-1",
    accountId: "fin-acc-3",
    type: "transfer",
    categoryId: "fin-cat-9",
    amount: 10000,
    description: "Перевод в копилку",
    tags: ["накопления"],
    date: daysAgo(10),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-11",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "income",
    categoryId: "fin-cat-10",
    amount: 35000,
    description: "Фриланс — сайт для кафе",
    tags: ["фриланс", "разработка"],
    date: daysAgo(12),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-12",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "fin-cat-2",
    amount: 3000,
    description: "Пополнение карты метро",
    tags: ["транспорт", "метро"],
    date: daysAgo(14),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-13",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "fin-cat-5",
    amount: 2000,
    description: "Подписка Spotify",
    tags: ["развлечения", "подписки"],
    date: daysAgo(15),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-14",
    userId: "user-1",
    accountId: "fin-acc-1",
    type: "expense",
    categoryId: "fin-cat-8",
    amount: 1500,
    description: "Стрижка",
    tags: ["услуги"],
    date: daysAgo(20),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-15",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "fin-cat-1",
    amount: 4200,
    description: "Доставка суши",
    tags: ["еда", "доставка"],
    date: daysAgo(25),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
];

const currentMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
const currentMonthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0);

export const mockFinanceBudgetPlans: BudgetPlan[] = [
  {
    id: "fin-budget-1",
    userId: "user-1",
    period: "month",
    periodStart: currentMonthStart.toISOString().split("T")[0],
    periodEnd: currentMonthEnd.toISOString().split("T")[0],
    expectedIncome: 185000,
    categoryBudgets: [
      { categoryId: "fin-cat-1", limit: 30000 },
      { categoryId: "fin-cat-2", limit: 10000 },
      { categoryId: "fin-cat-3", limit: 50000 },
      { categoryId: "fin-cat-4", limit: 15000 },
      { categoryId: "fin-cat-5", limit: 15000 },
      { categoryId: "fin-cat-6", limit: 10000 },
      { categoryId: "fin-cat-7", limit: 10000 },
      { categoryId: "fin-cat-8", limit: 10000 },
    ],
    createdAt: iso(currentMonthStart),
    updatedAt: iso(currentMonthStart),
  },
];

const nextYear = new Date(now.getFullYear() + 1, 0, 1);

export const mockFinanceGoals: FinanceGoal[] = [
  {
    id: "fin-goal-1",
    userId: "user-1",
    name: "Новый ноутбук",
    targetAmount: 150000,
    currentAmount: 45000,
    deadline: nextYear.toISOString().split("T")[0],
    priority: "high",
    accountId: "fin-acc-3",
    autoDepositPercent: 10,
    completed: false,
    createdAt: iso(new Date("2025-03-01")),
    updatedAt: iso(now),
  },
  {
    id: "fin-goal-2",
    userId: "user-1",
    name: "Путешествие",
    targetAmount: 200000,
    currentAmount: 80000,
    deadline: nextYear.toISOString().split("T")[0],
    priority: "medium",
    accountId: "fin-acc-3",
    autoDepositPercent: 5,
    completed: false,
    createdAt: iso(new Date("2025-01-15")),
    updatedAt: iso(now),
  },
];

export const mockFinanceLoans: Loan[] = [
  {
    id: "fin-loan-1",
    userId: "user-1",
    name: "Ипотека",
    totalAmount: 5000000,
    interestRate: 8,
    monthlyPayment: 45000,
    remainingAmount: 4200000,
    nextPaymentDate: new Date(now.getFullYear(), now.getMonth() + 1, 10)
      .toISOString()
      .split("T")[0],
    createdAt: iso(new Date("2023-06-01")),
    updatedAt: iso(now),
  },
];

export const mockFinanceProjects: FinanceProject[] = [
  {
    id: "fin-proj-1",
    userId: "user-1",
    name: "Ремонт",
    icon: "PaintBucket",
    targetAmount: 300000,
    savedAmount: 50000,
    deadline: "2026-12-31",
    description: "Косметический ремонт квартиры",
    linkedCategoryIds: ["fin-cat-3"],
    color: "blue",
    completed: false,
    createdAt: iso(new Date("2025-06-01")),
    updatedAt: iso(now),
  },
  {
    id: "fin-proj-2",
    userId: "user-1",
    name: "Новый MacBook",
    icon: "Laptop",
    targetAmount: 250000,
    savedAmount: 100000,
    deadline: "2026-09-01",
    description: "MacBook Pro M4",
    linkedCategoryIds: ["fin-cat-7"],
    color: "purple",
    completed: false,
    createdAt: iso(new Date("2025-05-15")),
    updatedAt: iso(now),
  },
];

export const mockFinanceEmergencyFund: EmergencyFund = {
  id: "fin-emergency-1",
  userId: "user-1",
  targetAmount: 300000,
  currentAmount: 120000,
};
