import type {
  FinanceAccount,
  TransactionCategory,
  Transaction,
  BudgetPlan,
  FinanceGoal,
  Loan,
  FinanceProject,
  EmergencyFund,
  ShoppingList,
} from "./finance-types";

const now = new Date();
const iso = (d: Date) => d.toISOString();
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
};

export const mockFinanceAccounts: FinanceAccount[] = [
  {
    id: "fin-acc-1",
    userId: "user-1",
    name: "Наличные",
    type: "cash",
    balance: 50000,
    currency: "RUB",
    sortOrder: 0,
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
  {
    id: "fin-acc-2",
    userId: "user-1",
    name: "Карта Т-Банк",
    type: "card",
    balance: 120000,
    currency: "RUB",
    sortOrder: 1,
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
  {
    id: "fin-acc-3",
    userId: "user-1",
    name: "Копилка",
    type: "savings",
    balance: 30000,
    currency: "RUB",
    sortOrder: 2,
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
  {
    id: "fin-acc-4",
    userId: "user-1",
    name: "Солана кошелёк",
    type: "crypto",
    balance: 200,
    currency: "USD",
    cryptoCoin: "SOL",
    cryptoAmount: 0.8,
    walletName: "Phantom",
    walletAddress: "0x1234567890abcdef1234567890abcdef12345678",
    url: "https://solscan.io/account/0x1234567890abcdef1234567890abcdef12345678",
    sortOrder: 3,
    createdAt: iso(new Date("2025-01-01")),
    updatedAt: iso(new Date("2025-01-01")),
  },
];

export const mockFinanceCategories: TransactionCategory[] = [
  // Расходы — Продукты и питание
  {
    id: "cat-grocery",
    userId: "user-1",
    name: "Магазин",
    icon: "ShoppingCart",
    type: "expense",
    color: "emerald",
  },
  {
    id: "cat-food-delivery",
    userId: "user-1",
    name: "Доставка продуктов",
    icon: "ShoppingCart",
    type: "expense",
    color: "emerald",
  },
  {
    id: "cat-meal-delivery",
    userId: "user-1",
    name: "Доставка готовой еды",
    icon: "Utensils",
    type: "expense",
    color: "emerald",
  },
  {
    id: "cat-coffee-shop",
    userId: "user-1",
    name: "Кофейня",
    icon: "Coffee",
    type: "expense",
    color: "emerald",
  },
  {
    id: "cat-cafe",
    userId: "user-1",
    name: "Кафе",
    icon: "Coffee",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-canteen",
    userId: "user-1",
    name: "Столовая",
    icon: "Soup",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-restaurant",
    userId: "user-1",
    name: "Ресторан",
    icon: "Utensils",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-fastfood",
    userId: "user-1",
    name: "Фастфуд",
    icon: "Sandwich",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-vending",
    userId: "user-1",
    name: "Вендинг",
    icon: "Coffee",
    type: "expense",
    color: "emerald",
  },
  {
    id: "cat-confectionery",
    userId: "user-1",
    name: "Кондитерская",
    icon: "Cake",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-food-other",
    userId: "user-1",
    name: "Иное (продукты)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Дом
  {
    id: "cat-rent",
    userId: "user-1",
    name: "Аренда",
    icon: "Home",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-utilities",
    userId: "user-1",
    name: "ЖКУ",
    icon: "ScrollText",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-electricity",
    userId: "user-1",
    name: "Электроэнергия",
    icon: "Zap",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-cold-water",
    userId: "user-1",
    name: "Водоснабжение (холодная вода)",
    icon: "Droplets",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-hot-water",
    userId: "user-1",
    name: "Горячая вода",
    icon: "Droplets",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-heating",
    userId: "user-1",
    name: "Отопление / Тепло",
    icon: "Flame",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-gas",
    userId: "user-1",
    name: "Газ",
    icon: "Flame",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-trash",
    userId: "user-1",
    name: "Вывоз мусора / ТКО",
    icon: "Trash2",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-major-repair",
    userId: "user-1",
    name: "Капитальный ремонт (взносы в фонд)",
    icon: "Wrench",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-home-maintenance",
    userId: "user-1",
    name: "Содержание и ремонт жилья",
    icon: "Wrench",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-common-areas",
    userId: "user-1",
    name: "Общедомовые нужды",
    icon: "ScrollText",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-heated-floor",
    userId: "user-1",
    name: "Теплый пол",
    icon: "Flame",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-cleaning",
    userId: "user-1",
    name: "Бытовая химия",
    icon: "Sparkles",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-furniture",
    userId: "user-1",
    name: "Мебель",
    icon: "Sofa",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-home-accessories",
    userId: "user-1",
    name: "Аксессуары (дом)",
    icon: "Gem",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-building-materials",
    userId: "user-1",
    name: "Стройматериалы",
    icon: "Hammer",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-appliances",
    userId: "user-1",
    name: "Бытовая техника",
    icon: "Zap",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-plant",
    userId: "user-1",
    name: "Растение",
    icon: "Flower2",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-home-other",
    userId: "user-1",
    name: "Иное (дом)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Связь и информационные услуги
  {
    id: "cat-internet",
    userId: "user-1",
    name: "Интернет",
    icon: "Wifi",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-mobile",
    userId: "user-1",
    name: "Мобильная связь",
    icon: "Smartphone",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-cable-tv",
    userId: "user-1",
    name: "Кабельное / Цифровое ТВ",
    icon: "Tv",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-antenna",
    userId: "user-1",
    name: "Антенна",
    icon: "Radio",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-subscriptions",
    userId: "user-1",
    name: "Подписки",
    icon: "Radio",
    type: "expense",
    color: "purple",
  },
  {
    id: "cat-intercom",
    userId: "user-1",
    name: "Домофон (абонентская плата)",
    icon: "Smartphone",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-phone",
    userId: "user-1",
    name: "Телефон (абонентская плата)",
    icon: "Smartphone",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-alarm",
    userId: "user-1",
    name: "Охранная сигнализация (мониторинг)",
    icon: "Lock",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-cloud",
    userId: "user-1",
    name: "Облачные хранилища",
    icon: "Cloud",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-vpn",
    userId: "user-1",
    name: "VPN",
    icon: "Lock",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-servers",
    userId: "user-1",
    name: "Серверы",
    icon: "Monitor",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-connectivity-other",
    userId: "user-1",
    name: "Иное (связь)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Транспорт
  {
    id: "cat-transit-pass",
    userId: "user-1",
    name: "Проездной",
    icon: "Bus",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-car",
    userId: "user-1",
    name: "Авто",
    icon: "Car",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-bicycle",
    userId: "user-1",
    name: "Велосипед",
    icon: "Bike",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-scooter",
    userId: "user-1",
    name: "Самокат",
    icon: "Scooter",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-kicksharing",
    userId: "user-1",
    name: "Кикшеринг",
    icon: "Scooter",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-carsharing",
    userId: "user-1",
    name: "Каршеринг",
    icon: "Car",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-motorcycle",
    userId: "user-1",
    name: "Мотоцикл",
    icon: "Shield",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-train",
    userId: "user-1",
    name: "Поезд/электричка",
    icon: "Train",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-metro",
    userId: "user-1",
    name: "Метро",
    icon: "Train",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-tram",
    userId: "user-1",
    name: "Трамвай",
    icon: "Train",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-trolleybus",
    userId: "user-1",
    name: "Троллейбус",
    icon: "Bus",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-taxi",
    userId: "user-1",
    name: "Такси",
    icon: "Car",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-plane",
    userId: "user-1",
    name: "Самолет",
    icon: "Plane",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-ship",
    userId: "user-1",
    name: "Корабль",
    icon: "Ship",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-fuel",
    userId: "user-1",
    name: "Топливо",
    icon: "Fuel",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-parking",
    userId: "user-1",
    name: "Платные парковки",
    icon: "ParkingCircle",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-traffic-fines",
    userId: "user-1",
    name: "Штрафы ГИБДД",
    icon: "Gavel",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-tolls",
    userId: "user-1",
    name: "Платные дороги",
    icon: "Car",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-car-wash",
    userId: "user-1",
    name: "Мойка",
    icon: "Droplets",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-car-service",
    userId: "user-1",
    name: "ТО",
    icon: "Wrench",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-car-repair",
    userId: "user-1",
    name: "Ремонт",
    icon: "Wrench",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-car-insurance",
    userId: "user-1",
    name: "Страховка (авто)",
    icon: "Shield",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-transport-tax",
    userId: "user-1",
    name: "Транспортный налог",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-tow-truck",
    userId: "user-1",
    name: "Эвакуатор",
    icon: "Car",
    type: "expense",
    color: "orange",
  },
  {
    id: "cat-transport-accessories",
    userId: "user-1",
    name: "Аксессуары (транспорт)",
    icon: "Gem",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-transport-other",
    userId: "user-1",
    name: "Иное (транспорт)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Медицина и здоровье
  {
    id: "cat-doctor",
    userId: "user-1",
    name: "Врач (прием, консультация)",
    icon: "Stethoscope",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-medication",
    userId: "user-1",
    name: "Таблетки (лекарства, витамины, БАДы)",
    icon: "Pill",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-gym",
    userId: "user-1",
    name: "Спортзал (абонемент, разовые посещения)",
    icon: "Dumbbell",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-lab-tests",
    userId: "user-1",
    name: "Анализы",
    icon: "Pill",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-pharmacy",
    userId: "user-1",
    name: "Аптека",
    icon: "Pill",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-massage",
    userId: "user-1",
    name: "Массаж",
    icon: "Heart",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-physiotherapy",
    userId: "user-1",
    name: "Физиотерапия",
    icon: "Heart",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-rehab",
    userId: "user-1",
    name: "Реабилитация / ЛФК",
    icon: "Heart",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-swimming-pool",
    userId: "user-1",
    name: "Бассейн (абонемент или разовое посещение)",
    icon: "Droplets",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-vaccination",
    userId: "user-1",
    name: "Вакцинация",
    icon: "Syringe",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-day-hospital",
    userId: "user-1",
    name: "Дневной стационар",
    icon: "Stethoscope",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-home-doctor",
    userId: "user-1",
    name: "Домашний вызов врача",
    icon: "Stethoscope",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-ambulance",
    userId: "user-1",
    name: "Скорая помощь",
    icon: "Heart",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-sanatorium",
    userId: "user-1",
    name: "Санаторий / Профилакторий",
    icon: "Heart",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-vitamins",
    userId: "user-1",
    name: "Витаминно-минеральные комплексы",
    icon: "Pill",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-procedures",
    userId: "user-1",
    name: "Процедуры",
    icon: "Stethoscope",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-health-other",
    userId: "user-1",
    name: "Иное (здоровье)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Одежда и аксессуары
  {
    id: "cat-clothes",
    userId: "user-1",
    name: "Одежда",
    icon: "Shirt",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-shoes",
    userId: "user-1",
    name: "Обувь",
    icon: "Footprints",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-jewelry",
    userId: "user-1",
    name: "Украшения",
    icon: "Gem",
    type: "expense",
    color: "purple",
  },
  {
    id: "cat-bags",
    userId: "user-1",
    name: "Сумки",
    icon: "Luggage",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-backpacks",
    userId: "user-1",
    name: "Рюкзаки",
    icon: "Backpack",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-luggage",
    userId: "user-1",
    name: "Чемоданы / Дорожные сумки",
    icon: "Luggage",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-belts",
    userId: "user-1",
    name: "Ремни",
    icon: "Shirt",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-ties",
    userId: "user-1",
    name: "Галстуки / Бабочки",
    icon: "Shirt",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-scarves",
    userId: "user-1",
    name: "Шарфы / Платки",
    icon: "Shirt",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-gloves",
    userId: "user-1",
    name: "Перчатки / Варежки",
    icon: "Shirt",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-hats",
    userId: "user-1",
    name: "Шапки / Кепки / Панамы",
    icon: "Shirt",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-socks",
    userId: "user-1",
    name: "Носки / Колготки / Чулки",
    icon: "Footprints",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-underwear",
    userId: "user-1",
    name: "Нижнее белье",
    icon: "Shirt",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-swimwear",
    userId: "user-1",
    name: "Купальники / Плавки",
    icon: "Shirt",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-sportswear",
    userId: "user-1",
    name: "Спортивная форма",
    icon: "Shirt",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-pajamas",
    userId: "user-1",
    name: "Пижамы / Домашняя одежда",
    icon: "Shirt",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-robes",
    userId: "user-1",
    name: "Халаты",
    icon: "Shirt",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-kids-clothes",
    userId: "user-1",
    name: "Детская одежда",
    icon: "Baby",
    type: "expense",
    color: "teal",
  },
  {
    id: "cat-hair-accessories",
    userId: "user-1",
    name: "Аксессуары для волос",
    icon: "Sparkles",
    type: "expense",
    color: "pink",
  },
  {
    id: "cat-sunglasses",
    userId: "user-1",
    name: "Очки солнцезащитные",
    icon: "Glasses",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-umbrellas",
    userId: "user-1",
    name: "Зонты",
    icon: "Umbrella",
    type: "expense",
    color: "blue",
  },
  {
    id: "cat-costume-jewelry",
    userId: "user-1",
    name: "Бижутерия",
    icon: "Gem",
    type: "expense",
    color: "purple",
  },
  {
    id: "cat-wallets",
    userId: "user-1",
    name: "Кошельки / Портмоне",
    icon: "Wallet",
    type: "expense",
    color: "violet",
  },
  {
    id: "cat-clothing-repair",
    userId: "user-1",
    name: "Ремонт одежды / обуви (химчистка, мастерская)",
    icon: "Wrench",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-clothing-other",
    userId: "user-1",
    name: "Иное (одежда)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Образование
  {
    id: "cat-training",
    userId: "user-1",
    name: "Обучение",
    icon: "GraduationCap",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-books",
    userId: "user-1",
    name: "Книги",
    icon: "BookOpen",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-textbooks",
    userId: "user-1",
    name: "Учебники / Учебные пособия",
    icon: "BookOpen",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-stationery",
    userId: "user-1",
    name: "Тетради / Блокноты / Письменные принадлежности",
    icon: "Pen",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-edu-subscriptions",
    userId: "user-1",
    name: "Подписка на образовательные платформы",
    icon: "Radio",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-tutor",
    userId: "user-1",
    name: "Репетитор / Преподаватель",
    icon: "GraduationCap",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-language-courses",
    userId: "user-1",
    name: "Языковые курсы",
    icon: "BookOpen",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-online-school",
    userId: "user-1",
    name: "Онлайн-школы / Академии",
    icon: "Monitor",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-university",
    userId: "user-1",
    name: "Вуз / Колледж",
    icon: "School",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-school",
    userId: "user-1",
    name: "Школа (частная / платные услуги)",
    icon: "School",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-kindergarten",
    userId: "user-1",
    name: "Детский сад (платный / частный)",
    icon: "Baby",
    type: "expense",
    color: "teal",
  },
  {
    id: "cat-clubs",
    userId: "user-1",
    name: "Кружки / Секции",
    icon: "Music",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-exams",
    userId: "user-1",
    name: "Экзамены / Тестирование (оплата за сдачу, сертификация)",
    icon: "ScrollText",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-certificates",
    userId: "user-1",
    name: "Дипломы / Сертификаты / Свидетельства",
    icon: "ScrollText",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-enrollment-fees",
    userId: "user-1",
    name: "Вступительные взносы",
    icon: "Banknote",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-library",
    userId: "user-1",
    name: "Библиотека (платный абонемент, штрафы)",
    icon: "BookOpen",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-office-supplies",
    userId: "user-1",
    name: "Канцелярия",
    icon: "Pen",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-printing",
    userId: "user-1",
    name: "Печать / Копирование / Брошюровка",
    icon: "Pen",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-flash-drives",
    userId: "user-1",
    name: "Портативные накопители (флешки, внешние диски)",
    icon: "Package",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-edu-apps",
    userId: "user-1",
    name: "Образовательные приложения (платные)",
    icon: "Smartphone",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-marathons",
    userId: "user-1",
    name: "Марафоны / Интенсивы (образовательные)",
    icon: "GraduationCap",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-conferences",
    userId: "user-1",
    name: "Конференции / Семинары (оплата участия)",
    icon: "Ticket",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-driving-school",
    userId: "user-1",
    name: "Вождение (автошкола, инструктор)",
    icon: "Car",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-mentor",
    userId: "user-1",
    name: "Тьютор / Наставник",
    icon: "GraduationCap",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-after-school",
    userId: "user-1",
    name: "Продленка",
    icon: "Baby",
    type: "expense",
    color: "teal",
  },
  {
    id: "cat-edu-other",
    userId: "user-1",
    name: "Иное (образование)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Развлечения
  {
    id: "cat-cinema",
    userId: "user-1",
    name: "Кино",
    icon: "Film",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-music",
    userId: "user-1",
    name: "Музыка",
    icon: "Music",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-games",
    userId: "user-1",
    name: "Игры",
    icon: "Gamepad2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-tickets",
    userId: "user-1",
    name: "Билеты",
    icon: "Ticket",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-theater",
    userId: "user-1",
    name: "Театр",
    icon: "Drama",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-concerts",
    userId: "user-1",
    name: "Концерты",
    icon: "Music",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-quests",
    userId: "user-1",
    name: "Квесты",
    icon: "Puzzle",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-amusement-rides",
    userId: "user-1",
    name: "Аттракционы",
    icon: "ParkingCircle",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-amusement-park",
    userId: "user-1",
    name: "Парки развлечений",
    icon: "PartyPopper",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-zoo",
    userId: "user-1",
    name: "Зоопарк",
    icon: "Cat",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-aquarium",
    userId: "user-1",
    name: "Океанариум",
    icon: "Ship",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-dolphinarium",
    userId: "user-1",
    name: "Дельфинарий",
    icon: "Ship",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-museum",
    userId: "user-1",
    name: "Музеи",
    icon: "Building2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-exhibitions",
    userId: "user-1",
    name: "Выставки",
    icon: "Building2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-circus",
    userId: "user-1",
    name: "Цирк",
    icon: "Drama",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-bowling",
    userId: "user-1",
    name: "Боулинг",
    icon: "Gamepad2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-billiards",
    userId: "user-1",
    name: "Бильярд",
    icon: "Gamepad2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-ice-rink",
    userId: "user-1",
    name: "Каток",
    icon: "Snowflake",
    type: "expense",
    color: "cyan",
  },
  {
    id: "cat-laser-tag",
    userId: "user-1",
    name: "Лазертаг",
    icon: "Target",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-paintball",
    userId: "user-1",
    name: "Пейнтбол",
    icon: "Target",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-water-park",
    userId: "user-1",
    name: "Аквапарк",
    icon: "Droplets",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-nightclubs",
    userId: "user-1",
    name: "Ночные клубы",
    icon: "Music",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-bars",
    userId: "user-1",
    name: "Бары",
    icon: "Coffee",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-casino",
    userId: "user-1",
    name: "Казино",
    icon: "Dices",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-slot-machines",
    userId: "user-1",
    name: "Игровые автоматы",
    icon: "Gamepad2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-holidays",
    userId: "user-1",
    name: "Праздники",
    icon: "PartyPopper",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-fireworks",
    userId: "user-1",
    name: "Фейерверки",
    icon: "Sparkles",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-photoshoot",
    userId: "user-1",
    name: "Фотосессии",
    icon: "Camera",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-streaming",
    userId: "user-1",
    name: "Подписки (развлечения)",
    icon: "Radio",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-video-games",
    userId: "user-1",
    name: "Видеоигры",
    icon: "Gamepad2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-consoles",
    userId: "user-1",
    name: "Игровые консоли",
    icon: "Gamepad2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-gaming-accessories",
    userId: "user-1",
    name: "Аксессуары для игр",
    icon: "Gamepad2",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-board-games",
    userId: "user-1",
    name: "Настольные игры",
    icon: "Dices",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-puzzles",
    userId: "user-1",
    name: "Пазлы",
    icon: "Puzzle",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-building-toys",
    userId: "user-1",
    name: "Конструкторы",
    icon: "ToyBrick",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-fiction",
    userId: "user-1",
    name: "Художественные книги",
    icon: "BookOpen",
    type: "expense",
    color: "indigo",
  },
  {
    id: "cat-photo-printing",
    userId: "user-1",
    name: "Печать фотографий",
    icon: "Camera",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-festivals",
    userId: "user-1",
    name: "Фестивали",
    icon: "Music",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-fairs",
    userId: "user-1",
    name: "Ярмарки",
    icon: "ShoppingCart",
    type: "expense",
    color: "amber",
  },
  {
    id: "cat-entertainment-other",
    userId: "user-1",
    name: "Иное (развлечения)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Госуслуги
  {
    id: "cat-documents",
    userId: "user-1",
    name: "Документы",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-fines",
    userId: "user-1",
    name: "Штрафы",
    icon: "AlertTriangle",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-taxes",
    userId: "user-1",
    name: "Налоги",
    icon: "Building2",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-fees",
    userId: "user-1",
    name: "Пошлины",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-licenses",
    userId: "user-1",
    name: "Лицензии",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-permits",
    userId: "user-1",
    name: "Разрешения",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-government-certificates",
    userId: "user-1",
    name: "Справки",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-international-passport",
    userId: "user-1",
    name: "Загранпаспорт",
    icon: "Globe",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-domestic-passport",
    userId: "user-1",
    name: "Внутренний паспорт",
    icon: "Globe",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-drivers-license",
    userId: "user-1",
    name: "Водительские права",
    icon: "Car",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-car-registration",
    userId: "user-1",
    name: "Регистрация автомобиля",
    icon: "Car",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-residence-registration",
    userId: "user-1",
    name: "Регистрация по месту жительства",
    icon: "Home",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-courts",
    userId: "user-1",
    name: "Суды",
    icon: "Gavel",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-enforcement-fees",
    userId: "user-1",
    name: "Исполнительные сборы",
    icon: "AlertTriangle",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-notary",
    userId: "user-1",
    name: "Нотариус",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-powers-of-attorney",
    userId: "user-1",
    name: "Доверенности",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-certified-copies",
    userId: "user-1",
    name: "Заверение копий",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-apostille",
    userId: "user-1",
    name: "Апостиль",
    icon: "Globe",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-document-translation",
    userId: "user-1",
    name: "Перевод документов",
    icon: "Globe",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-consular-fee",
    userId: "user-1",
    name: "Консульский сбор",
    icon: "Globe",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-visa",
    userId: "user-1",
    name: "Виза",
    icon: "Globe",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-certification",
    userId: "user-1",
    name: "Сертификация",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-meter-verification",
    userId: "user-1",
    name: "Поверка счетчиков",
    icon: "Zap",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-privatization",
    userId: "user-1",
    name: "Приватизация",
    icon: "Home",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-inheritance-processing",
    userId: "user-1",
    name: "Оформление наследства",
    icon: "Heart",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-deed-of-gift",
    userId: "user-1",
    name: "Дарственная",
    icon: "Gift",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-property-registration",
    userId: "user-1",
    name: "Купля-продажа недвижимости (регистрация)",
    icon: "Home",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-egrn-extracts",
    userId: "user-1",
    name: "Выписки из ЕГРН",
    icon: "ScrollText",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-cadastral-work",
    userId: "user-1",
    name: "Кадастровые работы",
    icon: "Home",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-property-appraisal",
    userId: "user-1",
    name: "Оценка имущества",
    icon: "Building2",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-state-expertise",
    userId: "user-1",
    name: "Госэкспертиза",
    icon: "Building2",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-excise-duties",
    userId: "user-1",
    name: "Акцизы",
    icon: "Building2",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-customs",
    userId: "user-1",
    name: "Таможенные платежи",
    icon: "Globe",
    type: "expense",
    color: "red",
  },
  {
    id: "cat-government-other",
    userId: "user-1",
    name: "Иное (госуслуги)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Дополнительно
  {
    id: "cat-service",
    userId: "user-1",
    name: "Услуга",
    icon: "Hand",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-purchase",
    userId: "user-1",
    name: "Покупка",
    icon: "ShoppingCart",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-rental-extra",
    userId: "user-1",
    name: "Аренда",
    icon: "Key",
    type: "expense",
    color: "slate",
  },
  // Расходы — Кредиты
  {
    id: "cat-loans",
    userId: "user-1",
    name: "Займы",
    icon: "Banknote",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-mortgage",
    userId: "user-1",
    name: "Ипотека",
    icon: "Home",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-car-loan",
    userId: "user-1",
    name: "Автокредит",
    icon: "Car",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-consumer-loan",
    userId: "user-1",
    name: "Потребительский кредит",
    icon: "Landmark",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-credit-card-debt",
    userId: "user-1",
    name: "Кредитная карта (погашение долга)",
    icon: "CreditCard",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-microloans",
    userId: "user-1",
    name: "Микрозаймы",
    icon: "Banknote",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-refinancing",
    userId: "user-1",
    name: "Рефинансирование",
    icon: "RefreshCw",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-loan-interest",
    userId: "user-1",
    name: "Проценты по кредиту",
    icon: "Percent",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-loan-issuance-fee",
    userId: "user-1",
    name: "Комиссия за выдачу кредита",
    icon: "Percent",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-loan-penalties",
    userId: "user-1",
    name: "Штрафы по кредиту (пеня, неустойка)",
    icon: "AlertTriangle",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-loan-insurance",
    userId: "user-1",
    name: "Страховка кредита",
    icon: "Shield",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-annuity",
    userId: "user-1",
    name: "Аннуитетный платеж",
    icon: "Landmark",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-differentiated",
    userId: "user-1",
    name: "Дифференцированный платеж",
    icon: "Landmark",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-early-repayment",
    userId: "user-1",
    name: "Досрочное погашение",
    icon: "Check",
    type: "expense",
    color: "green",
  },
  {
    id: "cat-loan-holidays",
    userId: "user-1",
    name: "Продление кредита / Каникулы",
    icon: "Calendar",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-overpayment",
    userId: "user-1",
    name: "Переплата по кредиту",
    icon: "Percent",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-debt-obligations",
    userId: "user-1",
    name: "Долговые обязательства (расписки, векселя)",
    icon: "ScrollText",
    type: "expense",
    color: "rose",
  },
  {
    id: "cat-loans-other",
    userId: "user-1",
    name: "Иное (кредиты)",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Расходы — Покупки и услуги
  {
    id: "cat-big-purchases",
    userId: "user-1",
    name: "Крупные покупки",
    icon: "Package",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-services",
    userId: "user-1",
    name: "Услуги",
    icon: "Hand",
    type: "expense",
    color: "slate",
  },
  {
    id: "cat-office",
    userId: "user-1",
    name: "Офис / Работа",
    icon: "Building2",
    type: "expense",
    color: "slate",
  },
  // Расходы — Страховки
  {
    id: "cat-insurance",
    userId: "user-1",
    name: "Страхование",
    icon: "Shield",
    type: "expense",
    color: "lime",
  },
  // Расходы — Прочее
  {
    id: "cat-other",
    userId: "user-1",
    name: "Прочие расходы",
    icon: "MoreHorizontal",
    type: "expense",
    color: "slate",
  },
  // Доходы — Зарплата и работа
  {
    id: "cat-salary",
    userId: "user-1",
    name: "Зарплата",
    icon: "DollarSign",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-salary-official",
    userId: "user-1",
    name: "Оклад",
    icon: "DollarSign",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-advance",
    userId: "user-1",
    name: "Аванс",
    icon: "Wallet",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-bonus",
    userId: "user-1",
    name: "Премия",
    icon: "Award",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-fee",
    userId: "user-1",
    name: "Гонорар",
    icon: "Crown",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-commission",
    userId: "user-1",
    name: "Комиссионные",
    icon: "Percent",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-parttime",
    userId: "user-1",
    name: "Подработка",
    icon: "Briefcase",
    type: "income",
    color: "emerald",
  },
  // Доходы — Инвестиционные доходы
  {
    id: "cat-investment",
    userId: "user-1",
    name: "Инвестиционный доход",
    icon: "TrendingUp",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-deposit-interest",
    userId: "user-1",
    name: "Процент по банковскому вкладу",
    icon: "PiggyBank",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-royalty",
    userId: "user-1",
    name: "Роялти",
    icon: "Crown",
    type: "income",
    color: "emerald",
  },
  {
    id: "cat-exchange-rate",
    userId: "user-1",
    name: "Курсовая разница",
    icon: "TrendingUp",
    type: "income",
    color: "emerald",
  },
  // Доходы — Возвраты и долги
  {
    id: "cat-debt-return",
    userId: "user-1",
    name: "Возвращение долга",
    icon: "Banknote",
    type: "income",
    color: "teal",
  },
  {
    id: "cat-overpayment-return",
    userId: "user-1",
    name: "Возврат переплаты",
    icon: "RefreshCw",
    type: "income",
    color: "teal",
  },
  {
    id: "cat-debt-forgiveness",
    userId: "user-1",
    name: "Прощение долга",
    icon: "Heart",
    type: "income",
    color: "teal",
  },
  {
    id: "cat-tax-deduction",
    userId: "user-1",
    name: "Налоговый вычет",
    icon: "Receipt",
    type: "income",
    color: "teal",
  },
  {
    id: "cat-tax-recalculation",
    userId: "user-1",
    name: "Перерасчет налога",
    icon: "ScrollText",
    type: "income",
    color: "teal",
  },
  // Доходы — Пособия и компенсации
  {
    id: "cat-scholarship",
    userId: "user-1",
    name: "Стипендия",
    icon: "GraduationCap",
    type: "income",
    color: "indigo",
  },
  {
    id: "cat-social-benefits",
    userId: "user-1",
    name: "Социальные пособия",
    icon: "Heart",
    type: "income",
    color: "pink",
  },
  {
    id: "cat-subsidy",
    userId: "user-1",
    name: "Субсидия",
    icon: "Building2",
    type: "income",
    color: "pink",
  },
  {
    id: "cat-maternity-capital",
    userId: "user-1",
    name: "Материнский капитал",
    icon: "Baby",
    type: "income",
    color: "pink",
  },
  {
    id: "cat-insurance-payout",
    userId: "user-1",
    name: "Страховые выплаты",
    icon: "Shield",
    type: "income",
    color: "pink",
  },
  {
    id: "cat-grant",
    userId: "user-1",
    name: "Гранты",
    icon: "Award",
    type: "income",
    color: "indigo",
  },
  {
    id: "cat-alimony",
    userId: "user-1",
    name: "Алименты",
    icon: "Heart",
    type: "income",
    color: "pink",
  },
  {
    id: "cat-compensation",
    userId: "user-1",
    name: "Компенсация",
    icon: "Hand",
    type: "income",
    color: "pink",
  },
  // Доходы — От имущества
  {
    id: "cat-rental",
    userId: "user-1",
    name: "Аренда",
    icon: "Key",
    type: "income",
    color: "blue",
  },
  {
    id: "cat-property-sale",
    userId: "user-1",
    name: "Продажа имущества",
    icon: "Building2",
    type: "income",
    color: "blue",
  },
  {
    id: "cat-item-sale",
    userId: "user-1",
    name: "Продажа вещи",
    icon: "Package",
    type: "income",
    color: "blue",
  },
  // Доходы — Кредиты и займы
  {
    id: "cat-loan-received",
    userId: "user-1",
    name: "Получение кредита/займа",
    icon: "Landmark",
    type: "income",
    color: "cyan",
  },
  // Доходы — Прочие доходы
  {
    id: "cat-gift",
    userId: "user-1",
    name: "Подарок",
    icon: "Gift",
    type: "income",
    color: "amber",
  },
  {
    id: "cat-winnings",
    userId: "user-1",
    name: "Выигрыши",
    icon: "Gem",
    type: "income",
    color: "amber",
  },
  {
    id: "cat-inheritance",
    userId: "user-1",
    name: "Наследство",
    icon: "Heart",
    type: "income",
    color: "amber",
  },
  {
    id: "cat-treasure",
    userId: "user-1",
    name: "Клад",
    icon: "Gem",
    type: "income",
    color: "amber",
  },
  {
    id: "cat-finding",
    userId: "user-1",
    name: "Находка",
    icon: "Search",
    type: "income",
    color: "amber",
  },
  {
    id: "cat-cashback",
    userId: "user-1",
    name: "Кэшбэк",
    icon: "RefreshCw",
    type: "income",
    color: "amber",
  },
];

export const mockFinanceTransactions: Transaction[] = [
  {
    id: "fin-tx-1",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-grocery",
    amount: 2500,
    description: "Продукты в Пятёрочке",
    tags: ["еда", "продукты"],
    date: daysAgo(1),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-2",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-taxi",
    amount: 1500,
    description: "Такси до офиса",
    tags: ["транспорт"],
    date: daysAgo(1),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-3",
    userId: "user-1",
    accountId: "fin-acc-1",
    type: "expense",
    categoryId: "cat-cinema",
    amount: 3500,
    description: "Кино с друзьями",
    tags: ["развлечения", "кино"],
    date: daysAgo(2),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-4",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "income",
    categoryId: "cat-salary",
    amount: 150000,
    description: "Зарплата за июнь",
    tags: ["зарплата"],
    date: daysAgo(3),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-5",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-rent",
    amount: 45000,
    description: "Аренда квартиры",
    tags: ["жильё", "аренда"],
    date: daysAgo(3),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-6",
    userId: "user-1",
    accountId: "fin-acc-1",
    type: "expense",
    categoryId: "cat-grocery",
    amount: 800,
    description: "Кофе и круассан",
    tags: ["еда", "кофе"],
    date: daysAgo(4),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-7",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-pharmacy",
    amount: 2200,
    description: "Аптека",
    tags: ["здоровье"],
    date: daysAgo(5),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-8",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-training",
    amount: 5000,
    description: "Курс по TypeScript",
    tags: ["образование"],
    date: daysAgo(7),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-9",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-clothes",
    amount: 6000,
    description: "Новые кроссовки",
    tags: ["одежда", "обувь"],
    date: daysAgo(8),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-10",
    userId: "user-1",
    accountId: "fin-acc-3",
    type: "transfer",
    categoryId: "cat-salary",
    amount: 10000,
    description: "Перевод в копилку",
    tags: ["накопления"],
    date: daysAgo(10),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-11",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "income",
    categoryId: "cat-parttime",
    amount: 35000,
    description: "Фриланс — сайт для кафе",
    tags: ["фриланс", "разработка"],
    date: daysAgo(12),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-12",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-metro",
    amount: 3000,
    description: "Пополнение карты метро",
    tags: ["транспорт", "метро"],
    date: daysAgo(14),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-13",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-streaming",
    amount: 2000,
    description: "Подписка Spotify",
    tags: ["развлечения", "подписки"],
    date: daysAgo(15),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-14",
    userId: "user-1",
    accountId: "fin-acc-1",
    type: "expense",
    categoryId: "cat-services",
    amount: 1500,
    description: "Стрижка",
    tags: ["услуги"],
    date: daysAgo(20),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
  {
    id: "fin-tx-15",
    userId: "user-1",
    accountId: "fin-acc-2",
    type: "expense",
    categoryId: "cat-food-delivery",
    amount: 4200,
    description: "Доставка суши",
    tags: ["еда", "доставка"],
    date: daysAgo(25),
    createdAt: iso(new Date()),
    updatedAt: iso(new Date()),
  },
];

const currentMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
const currentMonthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0);

export const mockFinanceBudgetPlans: BudgetPlan[] = [
  {
    id: "fin-budget-1",
    userId: "user-1",
    period: "month",
    periodStart: currentMonthStart.toISOString().split("T")[0],
    periodEnd: currentMonthEnd.toISOString().split("T")[0],
    expectedIncome: 185000,
    categoryBudgets: [
      { categoryId: "cat-grocery", limit: 30000 },
      { categoryId: "cat-food-delivery", limit: 5000 },
      { categoryId: "cat-restaurant", limit: 10000 },
      { categoryId: "cat-rent", limit: 45000 },
      { categoryId: "cat-utilities", limit: 8000 },
      { categoryId: "cat-taxi", limit: 5000 },
      { categoryId: "cat-car", limit: 5000 },
      { categoryId: "cat-metro", limit: 3000 },
      { categoryId: "cat-pharmacy", limit: 5000 },
      { categoryId: "cat-gym", limit: 5000 },
      { categoryId: "cat-clothes", limit: 10000 },
      { categoryId: "cat-other", limit: 5000 },
      { categoryId: "cat-cinema", limit: 5000 },
      { categoryId: "cat-streaming", limit: 3000 },
      { categoryId: "cat-training", limit: 10000 },
      { categoryId: "cat-mobile", limit: 2000 },
      { categoryId: "cat-gifts", limit: 5000 },
      { categoryId: "cat-mortgage", limit: 45000 },
      { categoryId: "cat-insurance", limit: 3000 },
      { categoryId: "cat-other", limit: 5000 },
    ],
    createdAt: iso(currentMonthStart),
    updatedAt: iso(currentMonthStart),
  },
];

const nextYear = new Date(now.getFullYear() + 1, 0, 1);

export const mockFinanceGoals: FinanceGoal[] = [
  {
    id: "fin-goal-1",
    userId: "user-1",
    name: "Новый ноутбук",
    targetAmount: 150000,
    currentAmount: 45000,
    deadline: nextYear.toISOString().split("T")[0],
    priority: "high",
    accountId: "fin-acc-3",
    autoDepositPercent: 10,
    completed: false,
    createdAt: iso(new Date("2025-03-01")),
    updatedAt: iso(now),
  },
  {
    id: "fin-goal-2",
    userId: "user-1",
    name: "Путешествие",
    targetAmount: 200000,
    currentAmount: 80000,
    deadline: nextYear.toISOString().split("T")[0],
    priority: "medium",
    accountId: "fin-acc-3",
    autoDepositPercent: 5,
    completed: false,
    createdAt: iso(new Date("2025-01-15")),
    updatedAt: iso(now),
  },
];

export const mockFinanceLoans: Loan[] = [
  {
    id: "fin-loan-1",
    userId: "user-1",
    name: "Ипотека",
    totalAmount: 5000000,
    interestRate: 8,
    monthlyPayment: 45000,
    remainingAmount: 4200000,
    nextPaymentDate: new Date(now.getFullYear(), now.getMonth() + 1, 10)
      .toISOString()
      .split("T")[0],
    repaymentType: "monthly",
    obligationType: "credit",
    overdueMonths: 0,
    createdAt: iso(new Date("2023-06-01")),
    updatedAt: iso(now),
  },
];

export const mockFinanceProjects: FinanceProject[] = [
  {
    id: "fin-proj-1",
    userId: "user-1",
    name: "Ремонт",
    icon: "PaintBucket",
    targetAmount: 300000,
    savedAmount: 50000,
    deadline: "2026-12-31",
    description: "Косметический ремонт квартиры",
    linkedCategoryIds: ["cat-rent"],
    color: "blue",
    completed: false,
    createdAt: iso(new Date("2025-06-01")),
    updatedAt: iso(now),
  },
  {
    id: "fin-proj-2",
    userId: "user-1",
    name: "Новый MacBook",
    icon: "Laptop",
    targetAmount: 250000,
    savedAmount: 100000,
    deadline: "2026-09-01",
    description: "MacBook Pro M4",
    linkedCategoryIds: ["cat-training"],
    color: "purple",
    completed: false,
    createdAt: iso(new Date("2025-05-15")),
    updatedAt: iso(now),
  },
];

export const mockFinanceEmergencyFund: EmergencyFund = {
  id: "fin-emergency-1",
  userId: "user-1",
  targetAmount: 300000,
  currentAmount: 120000,
};

export const mockShoppingLists: ShoppingList[] = [
  {
    id: "shop-1",
    userId: "user-1",
    name: "Продукты на неделю",
    date: new Date().toISOString().split("T")[0],
    items: [
      { id: "item-1", name: "Молоко", quantity: 2, unit: "л", checked: false },
      {
        id: "item-2",
        name: "Хлеб",
        quantity: 1,
        unit: "шт",
        checked: true,
        amount: 60,
        accountId: "fin-acc-2",
        transactionId: "fin-tx-1",
      },
      { id: "item-3", name: "Яйца", quantity: 10, unit: "шт", checked: false },
      { id: "item-4", name: "Сыр", quantity: 200, unit: "г", checked: false },
      {
        id: "item-5",
        name: "Масло сливочное",
        quantity: 1,
        unit: "шт",
        checked: false,
      },
    ],
    completed: false,
    archived: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "shop-2",
    userId: "user-1",
    name: "Стройматериалы",
    date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    items: [
      {
        id: "item-6",
        name: "Шпаклёвка",
        quantity: 2,
        unit: "кг",
        checked: false,
      },
      {
        id: "item-7",
        name: "Краска белая",
        quantity: 1,
        unit: "л",
        checked: false,
      },
      { id: "item-8", name: "Валик", quantity: 2, unit: "шт", checked: false },
    ],
    completed: false,
    archived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
