// Мок-данные для статического режима (без БД)
// Используются когда USE_DATABASE=false или БД недоступна

import {
  Board,
  BoardMember,
  Column,
  Comment,
  Company,
  PersonalTask,
  PersonalPlanEntry,
  Service,
  Task,
  ContentTask,
  PlannerChat,
} from "./models";

export const mockCompanies: Company[] = [
  {
    id: "company-1",
    name: "In Motion",
    color: "blue",
    icon: "Rocket",
    description: "Разработка основного продукта",
    ownerId: "user-1",
    members: ["user-1", "user-2", "user-3"],
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "company-2",
    name: "Маркетинг",
    color: "amber",
    icon: "Megaphone",
    description: "Продвижение и коммуникации",
    ownerId: "user-2",
    members: ["user-2", "user-3"],
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockBoards: Board[] = [
  {
    id: "board-1",
    name: "Разработка MVP",
    type: "team",
    companyId: "company-1",
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
    ownerId: "user-1",
    members: ["user-1", "user-2"],
    color: "blue",
    icon: "Rocket",
    pinned: true,
    order: 0,
  },
  {
    id: "board-2",
    name: "Маркетинг",
    type: "team",
    companyId: "company-2",
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
    ownerId: "user-2",
    members: ["user-2", "user-3"],
    color: "amber",
    icon: "Megaphone",
    order: 1,
  },
];

export const mockColumns: Column[] = [
  // Колонки для доски "Разработка MVP" (board-1)
  {
    id: "col-1",
    boardId: "board-1",
    name: "Нужно сделать",
    order: 0,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-2",
    boardId: "board-1",
    name: "В работе",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-3",
    boardId: "board-1",
    name: "Готово",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  // Колонки для доски "Маркетинг" (board-2)
  {
    id: "col-4",
    boardId: "board-2",
    name: "План",
    order: 0,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-5",
    boardId: "board-2",
    name: "В работе",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-6",
    boardId: "board-2",
    name: "Завершено",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockServices: Service[] = [
  {
    id: "mock-service-1",
    name: "API Gateway",
    description: "Шлюз для микросервисной архитектуры",
    status: "active",
    url: "https://api.example.com",
    createdAt: new Date("2024-01-15").toISOString(),
    updatedAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "mock-service-2",
    name: "Auth Service",
    description: "Сервис аутентификации и авторизации",
    status: "active",
    url: "https://auth.example.com",
    createdAt: new Date("2024-02-01").toISOString(),
    updatedAt: new Date("2024-02-01").toISOString(),
  },
  {
    id: "mock-service-3",
    name: "ML Pipeline",
    description: "Пайплайн для обработки данных с AI",
    status: "deploying",
    url: undefined,
    createdAt: new Date("2024-03-10").toISOString(),
    updatedAt: new Date("2024-03-10").toISOString(),
  },
];

export const mockTasks: Task[] = [
  // Задачи для доски "Разработка MVP" (board-1)
  {
    id: "task-1",
    boardId: "board-1",
    columnId: "col-1",
    title: "Дизайн главной страницы",
    description: "Разработать макет главной страницы в Figma",
    assignee: "Анна",
    assignees: ["Анна"],
    priority: "high",
    startDate: "2024-03-01",
    endDate: "2024-03-10",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-2",
    boardId: "board-1",
    columnId: "col-1",
    title: "Настройка CI/CD",
    description: "Настроить автоматическую сборку и деплой",
    assignee: "Иван",
    assignees: ["Иван"],
    priority: "medium",
    startDate: "2024-03-05",
    endDate: "2024-03-12",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-05").toISOString(),
    updatedAt: new Date("2024-03-05").toISOString(),
  },
  {
    id: "task-3",
    boardId: "board-1",
    columnId: "col-2",
    title: "API аутентификации",
    description: "Реализовать JWT аутентификацию",
    assignee: "Пётр",
    assignees: ["Пётр"],
    priority: "high",
    startDate: "2024-03-01",
    endDate: "2024-03-08",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-4",
    boardId: "board-1",
    columnId: "col-2",
    title: "База данных пользователей",
    description: "Спроектировать и создать схему БД",
    assignee: "Мария",
    assignees: ["Мария", "Пётр"],
    priority: "medium",
    startDate: "2024-03-01",
    endDate: "2024-03-07",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-5",
    boardId: "board-1",
    columnId: "col-3",
    title: "Репозиторий проекта",
    description: "Создать репозиторий и настроить доступы",
    assignee: "Иван",
    assignees: ["Иван"],
    priority: "low",
    startDate: "2024-02-20",
    endDate: "2024-02-25",
    completed: true,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-02-20").toISOString(),
    updatedAt: new Date("2024-02-25").toISOString(),
  },
  {
    id: "task-6",
    boardId: "board-1",
    columnId: "col-3",
    title: "Выбор технологического стека",
    description: "Определиться с технологиями для проекта",
    assignee: "Команда",
    assignees: [],
    priority: "medium",
    startDate: "2024-02-15",
    endDate: "2024-02-20",
    completed: true,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-02-15").toISOString(),
    updatedAt: new Date("2024-02-20").toISOString(),
  },
  {
    id: "task-7",
    boardId: "board-1",
    columnId: "col-3",
    title: "Написание технической документации",
    description: "Составить документацию по API и архитектуре",
    assignee: "Мария",
    assignees: ["Мария"],
    priority: "medium",
    startDate: "2024-02-10",
    endDate: "2024-02-18",
    completed: true,
    archived: true,
    archivedAt: null,
    createdAt: new Date("2024-02-10").toISOString(),
    updatedAt: new Date("2024-02-18").toISOString(),
  },
  {
    id: "task-8",
    boardId: "board-1",
    columnId: "col-3",
    title: "Интеграционное тестирование",
    description: "Провести интеграционное тестирование модулей",
    assignee: "Пётр",
    assignees: ["Пётр", "Иван"],
    priority: "high",
    startDate: "2024-02-05",
    endDate: "2024-02-12",
    completed: true,
    archived: true,
    archivedAt: null,
    createdAt: new Date("2024-02-05").toISOString(),
    updatedAt: new Date("2024-02-12").toISOString(),
  },
  // Задачи для доски "Маркетинг" (board-2)
  {
    id: "task-9",
    boardId: "board-2",
    columnId: "col-4",
    title: "Анализ целевой аудитории",
    description: "Провести исследование ЦА",
    assignee: "Алексей",
    assignees: ["Алексей", "Елена"],
    priority: "high",
    startDate: "2024-03-01",
    endDate: "2024-03-15",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-10",
    boardId: "board-2",
    columnId: "col-4",
    title: "Конкурентный анализ",
    description: "Изучить предложения конкурентов",
    assignee: "Елена",
    assignees: ["Елена"],
    priority: "medium",
    startDate: "2024-03-05",
    endDate: "2024-03-12",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-05").toISOString(),
    updatedAt: new Date("2024-03-05").toISOString(),
  },
  {
    id: "task-11",
    boardId: "board-2",
    columnId: "col-5",
    title: "Запуск рекламной кампании",
    description: "Настроить таргетированную рекламу",
    assignee: "Алексей",
    assignees: ["Алексей"],
    priority: "medium",
    startDate: "2024-03-10",
    endDate: "2024-03-20",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-10").toISOString(),
    updatedAt: new Date("2024-03-10").toISOString(),
  },
  {
    id: "task-12",
    boardId: "board-2",
    columnId: "col-6",
    title: "Подготовка отчёта",
    description: "Составить отчёт по итогам кампании",
    assignee: "Елена",
    assignees: ["Елена"],
    priority: "low",
    startDate: "2024-02-20",
    endDate: "2024-02-28",
    completed: true,
    archived: true,
    archivedAt: null,
    createdAt: new Date("2024-02-20").toISOString(),
    updatedAt: new Date("2024-02-28").toISOString(),
  },
];

export const mockComments: Comment[] = [
  {
    id: "comment-1",
    taskId: "task-1",
    author: "Анна",
    text: "Начала работу над макетом, черновик готов на 50%",
    createdAt: new Date("2024-03-02").toISOString(),
  },
  {
    id: "comment-2",
    taskId: "task-1",
    author: "Иван",
    text: "Не забудь добавить секцию с преимуществами",
    createdAt: new Date("2024-03-03").toISOString(),
  },
  {
    id: "comment-3",
    taskId: "task-3",
    author: "Пётр",
    text: "JWT токены готовы, осталось добавить refresh",
    createdAt: new Date("2024-03-04").toISOString(),
  },
];

export const mockPersonalTasks: PersonalTask[] = [
  {
    id: "ptask-1",
    date: "2026-07-13",
    startTime: "09:00",
    endTime: "10:30",
    title: "Планёрка с командой",
    priority: "high",
    completed: false,
    comment: "Обсудить спринт и распределить задачи",
    createdAt: new Date("2026-07-13").toISOString(),
    updatedAt: new Date("2026-07-13").toISOString(),
    boardId: "board-1",
  },
  {
    id: "ptask-2",
    date: "2026-07-13",
    startTime: "14:00",
    endTime: "15:00",
    title: "Подготовить отчёт",
    priority: "medium",
    completed: false,
    comment: "Отчёт по итогам месяца для руководства",
    createdAt: new Date("2026-07-13").toISOString(),
    updatedAt: new Date("2026-07-13").toISOString(),
    boardId: "board-1",
  },
  {
    id: "ptask-3",
    date: "2026-07-14",
    startTime: "10:00",
    endTime: "12:00",
    title: "Работа над проектом",
    priority: "high",
    completed: true,
    createdAt: new Date("2026-07-14").toISOString(),
    updatedAt: new Date("2026-07-14").toISOString(),
    boardId: "board-1",
  },
  {
    id: "ptask-4",
    date: "2026-07-15",
    startTime: "11:00",
    endTime: "11:30",
    title: "Созвон с заказчиком",
    priority: "high",
    completed: false,
    comment: "Уточнить требования по новому модулю",
    createdAt: new Date("2026-07-15").toISOString(),
    updatedAt: new Date("2026-07-15").toISOString(),
    boardId: "board-1",
  },
  {
    id: "ptask-5",
    date: "2026-07-16",
    startTime: "15:00",
    endTime: "16:00",
    title: "Тренировка",
    priority: "low",
    completed: false,
    createdAt: new Date("2026-07-16").toISOString(),
    updatedAt: new Date("2026-07-16").toISOString(),
    boardId: "board-2",
  },
];

export const mockContentTasks: ContentTask[] = [
  {
    id: "content-1",
    title: "Разбор: 3 ошибки в продающих постах",
    topic: "Разбор ошибок",
    platform: "Telegram",
    funnel: false,
    format: "Пост",
    status: "Готов к публикации",
    date: "2026-08-12",
    time: "11:00",
    notes: "Тезисы: структура оффера, боль, решение. Ссылка на кейс.",
    completed: false,
    createdAt: new Date("2026-08-10").toISOString(),
    updatedAt: new Date("2026-08-10").toISOString(),
    ownerId: "user-1",
  },
  {
    id: "content-2",
    title: "Лайфхак для утренней рутины",
    topic: "Мотивация / вдохновение",
    platform: "Instagram",
    funnel: true,
    format: "Reels / Shorts",
    status: "В работе",
    date: "2026-08-14",
    time: "18:30",
    notes: "Сценарий: 15 сек, крупные планы. ТЗ для монтажёра в комментарии.",
    completed: false,
    createdAt: new Date("2026-08-11").toISOString(),
    updatedAt: new Date("2026-08-11").toISOString(),
    ownerId: "user-1",
  },
  {
    id: "content-3",
    title: "Запуск новой тарифной линейки",
    topic: "Анонс запуска",
    platform: "YouTube",
    funnel: false,
    format: "Видео",
    status: "Черновик",
    date: "2026-08-16",
    time: "12:00",
    notes: "Нарезка интервью + титры. Хронометраж 4-5 минут.",
    completed: false,
    createdAt: new Date("2026-08-12").toISOString(),
    updatedAt: new Date("2026-08-12").toISOString(),
    ownerId: "user-1",
  },
  {
    id: "content-4",
    title: "Кейс клиента: рост трафика в 2 раза",
    topic: "Кейсы клиентов",
    platform: "VC.ru",
    funnel: true,
    format: "Кейс",
    status: "Идея",
    date: null,
    time: null,
    notes: "Собрать цифры у клиента, разрешить публикацию.",
    completed: false,
    createdAt: new Date("2026-08-09").toISOString(),
    updatedAt: new Date("2026-08-09").toISOString(),
    ownerId: "user-1",
  },
  {
    id: "content-5",
    title: "Подборка сервисов для контент-мейкеров",
    topic: "Подборка",
    platform: "Telegram",
    funnel: false,
    format: "Подборка",
    status: "Идея",
    date: null,
    time: null,
    notes: "5-7 сервисов: монтаж, обложки, тайминг.",
    completed: false,
    createdAt: new Date("2026-08-08").toISOString(),
    updatedAt: new Date("2026-08-08").toISOString(),
    ownerId: "user-1",
  },
  {
    id: "content-6",
    title: "Интервью с продакт-менеджером",
    topic: "Команда",
    platform: "YouTube",
    funnel: false,
    format: "Интервью",
    status: "Идея",
    date: null,
    time: null,
    notes: "Список вопросов: путь в продукте, инструменты, ошибки.",
    completed: false,
    createdAt: new Date("2026-08-07").toISOString(),
    updatedAt: new Date("2026-08-07").toISOString(),
    ownerId: "user-1",
  },
];

export const mockPlannerChats: PlannerChat[] = [];

export const mockBoardMembers: BoardMember[] = [
  {
    id: "member-1",
    boardId: "board-1",
    name: "Анна",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "member-2",
    boardId: "board-1",
    name: "Иван",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "member-3",
    boardId: "board-1",
    name: "Пётр",
    createdAt: new Date("2024-01-02").toISOString(),
  },
  {
    id: "member-4",
    boardId: "board-1",
    name: "Мария",
    createdAt: new Date("2024-01-02").toISOString(),
  },
  {
    id: "member-5",
    boardId: "board-2",
    name: "Алексей",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "member-6",
    boardId: "board-2",
    name: "Елена",
    createdAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockPersonalPlanEntries: PersonalPlanEntry[] = [
  {
    id: "plan-1",
    date: new Date().toISOString().split("T")[0],
    startTime: "08:00",
    endTime: "08:15",
    title: "Подъём",
    priority: "medium",
    completed: true,
    comment: "Застелить кровать, умыться",
    sortOrder: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "plan-2",
    date: new Date().toISOString().split("T")[0],
    startTime: "09:00",
    endTime: "09:30",
    title: "Зарядка",
    priority: "low",
    completed: false,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
