// Мок-данные для статического режима (без БД)
// Используются когда USE_DATABASE=false или БД недоступна

import {
  Board,
  BoardMember,
  Column,
  Comment,
  PersonalTask,
  Service,
  Task,
} from "./models";

export const mockBoards: Board[] = [
  {
    id: "board-1",
    name: "Разработка MVP",
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "board-2",
    name: "Маркетинг",
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockColumns: Column[] = [
  {
    id: "col-1",
    boardId: "board-1",
    name: "Нужно сделать",
    order: 0,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-2",
    boardId: "board-1",
    name: "В работе",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-3",
    boardId: "board-1",
    name: "Готово",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockServices: Service[] = [
  {
    id: "mock-service-1",
    name: "API Gateway",
    description: "Шлюз для микросервисной архитектуры",
    status: "active",
    url: "https://api.example.com",
    createdAt: new Date("2024-01-15").toISOString(),
    updatedAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "mock-service-2",
    name: "Auth Service",
    description: "Сервис аутентификации и авторизации",
    status: "active",
    url: "https://auth.example.com",
    createdAt: new Date("2024-02-01").toISOString(),
    updatedAt: new Date("2024-02-01").toISOString(),
  },
  {
    id: "mock-service-3",
    name: "ML Pipeline",
    description: "Пайплайн для обработки данных с AI",
    status: "deploying",
    url: undefined,
    createdAt: new Date("2024-03-10").toISOString(),
    updatedAt: new Date("2024-03-10").toISOString(),
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    columnId: "col-1",
    title: "Дизайн главной страницы",
    description: "Разработать макет главной страницы в Figma",
    assignee: "Анна",
    startDate: "2024-03-01",
    endDate: "2024-03-10",
    completed: false,
    archived: false,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-2",
    columnId: "col-1",
    title: "Настройка CI/CD",
    description: "Настроить автоматическую сборку и деплой",
    assignee: "Иван",
    startDate: "2024-03-05",
    endDate: "2024-03-12",
    completed: false,
    archived: false,
    createdAt: new Date("2024-03-05").toISOString(),
    updatedAt: new Date("2024-03-05").toISOString(),
  },
  {
    id: "task-3",
    columnId: "col-2",
    title: "API аутентификации",
    description: "Реализовать JWT аутентификацию",
    assignee: "Пётр",
    startDate: "2024-03-01",
    endDate: "2024-03-08",
    completed: false,
    archived: false,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-4",
    columnId: "col-2",
    title: "База данных пользователей",
    description: "Спроектировать и создать схему БД",
    assignee: "Мария",
    startDate: "2024-03-01",
    endDate: "2024-03-07",
    completed: false,
    archived: false,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-5",
    columnId: "col-3",
    title: "Репозиторий проекта",
    description: "Создать репозиторий и настроить доступы",
    assignee: "Иван",
    startDate: "2024-02-20",
    endDate: "2024-02-25",
    completed: true,
    archived: false,
    createdAt: new Date("2024-02-20").toISOString(),
    updatedAt: new Date("2024-02-25").toISOString(),
  },
  {
    id: "task-6",
    columnId: "col-3",
    title: "Выбор технологического стека",
    description: "Определиться с технологиями для проекта",
    assignee: "Команда",
    startDate: "2024-02-15",
    endDate: "2024-02-20",
    completed: true,
    archived: false,
    createdAt: new Date("2024-02-15").toISOString(),
    updatedAt: new Date("2024-02-20").toISOString(),
  },
  {
    id: "task-7",
    columnId: "col-3",
    title: "Написание технической документации",
    description: "Составить документацию по API и архитектуре",
    assignee: "Мария",
    startDate: "2024-02-10",
    endDate: "2024-02-18",
    completed: true,
    archived: true,
    createdAt: new Date("2024-02-10").toISOString(),
    updatedAt: new Date("2024-02-18").toISOString(),
  },
  {
    id: "task-8",
    columnId: "col-3",
    title: "Интеграционное тестирование",
    description: "Провести интеграционное тестирование модулей",
    assignee: "Пётр",
    startDate: "2024-02-05",
    endDate: "2024-02-12",
    completed: true,
    archived: true,
    createdAt: new Date("2024-02-05").toISOString(),
    updatedAt: new Date("2024-02-12").toISOString(),
  },
];

export const mockComments: Comment[] = [
  {
    id: "comment-1",
    taskId: "task-1",
    author: "Анна",
    text: "Начала работу над макетом, черновик готов на 50%",
    createdAt: new Date("2024-03-02").toISOString(),
  },
  {
    id: "comment-2",
    taskId: "task-1",
    author: "Иван",
    text: "Не забудь добавить секцию с преимуществами",
    createdAt: new Date("2024-03-03").toISOString(),
  },
  {
    id: "comment-3",
    taskId: "task-3",
    author: "Пётр",
    text: "JWT токены готовы, осталось добавить refresh",
    createdAt: new Date("2024-03-04").toISOString(),
  },
];

export const mockPersonalTasks: PersonalTask[] = [
  {
    id: "ptask-1",
    dayOfWeek: 0,
    startTime: "09:00",
    endTime: "10:30",
    title: "Планёрка с командой",
    priority: "high",
    completed: false,
    comment: "Обсудить спринт и распределить задачи",
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-2",
    dayOfWeek: 0,
    startTime: "14:00",
    endTime: "15:00",
    title: "Подготовить отчёт",
    priority: "medium",
    completed: false,
    comment: "Отчёт по итогам месяца для руководства",
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-3",
    dayOfWeek: 1,
    startTime: "10:00",
    endTime: "12:00",
    title: "Работа над проектом",
    priority: "high",
    completed: true,
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-4",
    dayOfWeek: 2,
    startTime: "11:00",
    endTime: "11:30",
    title: "Созвон с заказчиком",
    priority: "high",
    completed: false,
    comment: "Уточнить требования по новому модулю",
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-5",
    dayOfWeek: 3,
    startTime: "15:00",
    endTime: "16:00",
    title: "Тренировка",
    priority: "low",
    completed: false,
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-6",
    dayOfWeek: 4,
    startTime: "18:00",
    endTime: "19:00",
    title: "Чтение книги",
    priority: "low",
    completed: false,
    comment: "Глава 5-6",
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-7",
    dayOfWeek: 0,
    startTime: "08:00",
    endTime: "08:30",
    title: "Утренняя зарядка",
    priority: "low",
    completed: false,
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-8",
    dayOfWeek: 1,
    startTime: "09:00",
    endTime: "10:00",
    title: "Собеседование",
    priority: "high",
    completed: false,
    comment: "Кандидат на позицию Frontend-разработчика",
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-9",
    dayOfWeek: 2,
    startTime: "09:00",
    endTime: "10:00",
    title: "Обзор кода",
    priority: "medium",
    completed: false,
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-10",
    dayOfWeek: 3,
    startTime: "10:00",
    endTime: "11:00",
    title: "Написание документации",
    priority: "medium",
    completed: false,
    comment: "API-документация для нового эндпоинта",
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-11",
    dayOfWeek: 4,
    startTime: "09:00",
    endTime: "10:00",
    title: "Ретроспектива",
    priority: "medium",
    completed: false,
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-12",
    dayOfWeek: 5,
    startTime: "11:00",
    endTime: "12:00",
    title: "Планирование выходных",
    priority: "low",
    completed: false,
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
  {
    id: "ptask-13",
    dayOfWeek: 6,
    startTime: "10:00",
    endTime: "11:00",
    title: "Отдых",
    priority: "low",
    completed: true,
    createdAt: new Date("2024-06-01").toISOString(),
    updatedAt: new Date("2024-06-01").toISOString(),
  },
];

export const mockBoardMembers: BoardMember[] = [
  {
    id: "member-1",
    boardId: "board-1",
    name: "Анна",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "member-2",
    boardId: "board-1",
    name: "Иван",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "member-3",
    boardId: "board-1",
    name: "Пётр",
    createdAt: new Date("2024-01-02").toISOString(),
  },
  {
    id: "member-4",
    boardId: "board-1",
    name: "Мария",
    createdAt: new Date("2024-01-02").toISOString(),
  },
  {
    id: "member-5",
    boardId: "board-2",
    name: "Алексей",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "member-6",
    boardId: "board-2",
    name: "Елена",
    createdAt: new Date("2024-01-01").toISOString(),
  },
];
