// Мок-данные для статического режима (без БД)
// Используются когда USE_DATABASE=false или БД недоступна

import {
  Board,
  BoardMember,
  Column,
  Comment,
  Note,
  PersonalTask,
  Service,
  Task,
} from "./models";

export const mockBoards: Board[] = [
  {
    id: "board-1",
    name: "Разработка MVP",
    type: "team",
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
    ownerId: "user-1",
    members: ["user-1", "user-2"],
    color: "blue",
    icon: "Rocket",
    pinned: true,
    order: 0,
  },
  {
    id: "board-2",
    name: "Маркетинг",
    type: "team",
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
    ownerId: "user-2",
    members: ["user-2", "user-3"],
    color: "amber",
    icon: "Megaphone",
    order: 1,
  },
];

export const mockColumns: Column[] = [
  // Колонки для доски "Разработка MVP" (board-1)
  {
    id: "col-1",
    boardId: "board-1",
    name: "Нужно сделать",
    order: 0,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-2",
    boardId: "board-1",
    name: "В работе",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-3",
    boardId: "board-1",
    name: "Готово",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  // Колонки для доски "Маркетинг" (board-2)
  {
    id: "col-4",
    boardId: "board-2",
    name: "План",
    order: 0,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-5",
    boardId: "board-2",
    name: "В работе",
    order: 1,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "col-6",
    boardId: "board-2",
    name: "Завершено",
    order: 2,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
];

export const mockServices: Service[] = [
  {
    id: "mock-service-1",
    name: "API Gateway",
    description: "Шлюз для микросервисной архитектуры",
    status: "active",
    url: "https://api.example.com",
    createdAt: new Date("2024-01-15").toISOString(),
    updatedAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "mock-service-2",
    name: "Auth Service",
    description: "Сервис аутентификации и авторизации",
    status: "active",
    url: "https://auth.example.com",
    createdAt: new Date("2024-02-01").toISOString(),
    updatedAt: new Date("2024-02-01").toISOString(),
  },
  {
    id: "mock-service-3",
    name: "ML Pipeline",
    description: "Пайплайн для обработки данных с AI",
    status: "deploying",
    url: undefined,
    createdAt: new Date("2024-03-10").toISOString(),
    updatedAt: new Date("2024-03-10").toISOString(),
  },
];

export const mockTasks: Task[] = [
  // Задачи для доски "Разработка MVP" (board-1)
  {
    id: "task-1",
    boardId: "board-1",
    columnId: "col-1",
    title: "Дизайн главной страницы",
    description: "Разработать макет главной страницы в Figma",
    assignee: "Анна",
    assignees: ["Анна"],
    priority: "high",
    startDate: "2024-03-01",
    endDate: "2024-03-10",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-2",
    boardId: "board-1",
    columnId: "col-1",
    title: "Настройка CI/CD",
    description: "Настроить автоматическую сборку и деплой",
    assignee: "Иван",
    assignees: ["Иван"],
    priority: "medium",
    startDate: "2024-03-05",
    endDate: "2024-03-12",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-05").toISOString(),
    updatedAt: new Date("2024-03-05").toISOString(),
  },
  {
    id: "task-3",
    boardId: "board-1",
    columnId: "col-2",
    title: "API аутентификации",
    description: "Реализовать JWT аутентификацию",
    assignee: "Пётр",
    assignees: ["Пётр"],
    priority: "high",
    startDate: "2024-03-01",
    endDate: "2024-03-08",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-4",
    boardId: "board-1",
    columnId: "col-2",
    title: "База данных пользователей",
    description: "Спроектировать и создать схему БД",
    assignee: "Мария",
    assignees: ["Мария", "Пётр"],
    priority: "medium",
    startDate: "2024-03-01",
    endDate: "2024-03-07",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-5",
    boardId: "board-1",
    columnId: "col-3",
    title: "Репозиторий проекта",
    description: "Создать репозиторий и настроить доступы",
    assignee: "Иван",
    assignees: ["Иван"],
    priority: "low",
    startDate: "2024-02-20",
    endDate: "2024-02-25",
    completed: true,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-02-20").toISOString(),
    updatedAt: new Date("2024-02-25").toISOString(),
  },
  {
    id: "task-6",
    boardId: "board-1",
    columnId: "col-3",
    title: "Выбор технологического стека",
    description: "Определиться с технологиями для проекта",
    assignee: "Команда",
    assignees: [],
    priority: "medium",
    startDate: "2024-02-15",
    endDate: "2024-02-20",
    completed: true,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-02-15").toISOString(),
    updatedAt: new Date("2024-02-20").toISOString(),
  },
  {
    id: "task-7",
    boardId: "board-1",
    columnId: "col-3",
    title: "Написание технической документации",
    description: "Составить документацию по API и архитектуре",
    assignee: "Мария",
    assignees: ["Мария"],
    priority: "medium",
    startDate: "2024-02-10",
    endDate: "2024-02-18",
    completed: true,
    archived: true,
    archivedAt: null,
    createdAt: new Date("2024-02-10").toISOString(),
    updatedAt: new Date("2024-02-18").toISOString(),
  },
  {
    id: "task-8",
    boardId: "board-1",
    columnId: "col-3",
    title: "Интеграционное тестирование",
    description: "Провести интеграционное тестирование модулей",
    assignee: "Пётр",
    assignees: ["Пётр", "Иван"],
    priority: "high",
    startDate: "2024-02-05",
    endDate: "2024-02-12",
    completed: true,
    archived: true,
    archivedAt: null,
    createdAt: new Date("2024-02-05").toISOString(),
    updatedAt: new Date("2024-02-12").toISOString(),
  },
  // Задачи для доски "Маркетинг" (board-2)
  {
    id: "task-9",
    boardId: "board-2",
    columnId: "col-4",
    title: "Анализ целевой аудитории",
    description: "Провести исследование ЦА",
    assignee: "Алексей",
    assignees: ["Алексей", "Елена"],
    priority: "high",
    startDate: "2024-03-01",
    endDate: "2024-03-15",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-01").toISOString(),
    updatedAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "task-10",
    boardId: "board-2",
    columnId: "col-4",
    title: "Конкурентный анализ",
    description: "Изучить предложения конкурентов",
    assignee: "Елена",
    assignees: ["Елена"],
    priority: "medium",
    startDate: "2024-03-05",
    endDate: "2024-03-12",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-05").toISOString(),
    updatedAt: new Date("2024-03-05").toISOString(),
  },
  {
    id: "task-11",
    boardId: "board-2",
    columnId: "col-5",
    title: "Запуск рекламной кампании",
    description: "Настроить таргетированную рекламу",
    assignee: "Алексей",
    assignees: ["Алексей"],
    priority: "medium",
    startDate: "2024-03-10",
    endDate: "2024-03-20",
    completed: false,
    archived: false,
    archivedAt: null,
    createdAt: new Date("2024-03-10").toISOString(),
    updatedAt: new Date("2024-03-10").toISOString(),
  },
  {
    id: "task-12",
    boardId: "board-2",
    columnId: "col-6",
    title: "Подготовка отчёта",
    description: "Составить отчёт по итогам кампании",
    assignee: "Елена",
    assignees: ["Елена"],
    priority: "low",
    startDate: "2024-02-20",
    endDate: "2024-02-28",
    completed: true,
    archived: true,
    archivedAt: null,
    createdAt: new Date("2024-02-20").toISOString(),
    updatedAt: new Date("2024-02-28").toISOString(),
  },
];

export const mockComments: Comment[] = [
  {
    id: "comment-1",
    taskId: "task-1",
    author: "Анна",
    text: "Начала работу над макетом, черновик готов на 50%",
    createdAt: new Date("2024-03-02").toISOString(),
  },
  {
    id: "comment-2",
    taskId: "task-1",
    author: "Иван",
    text: "Не забудь добавить секцию с преимуществами",
    createdAt: new Date("2024-03-03").toISOString(),
  },
  {
    id: "comment-3",
    taskId: "task-3",
    author: "Пётр",
    text: "JWT токены готовы, осталось добавить refresh",
    createdAt: new Date("2024-03-04").toISOString(),
  },
];

export const mockPersonalTasks: PersonalTask[] = [
  {
    id: "ptask-1",
    date: "2026-07-13",
    startTime: "09:00",
    endTime: "10:30",
    title: "Планёрка с командой",
    priority: "high",
    completed: false,
    comment: "Обсудить спринт и распределить задачи",
    createdAt: new Date("2026-07-13").toISOString(),
    updatedAt: new Date("2026-07-13").toISOString(),
    boardId: "board-1",
  },
  {
    id: "ptask-2",
    date: "2026-07-13",
    startTime: "14:00",
    endTime: "15:00",
    title: "Подготовить отчёт",
    priority: "medium",
    completed: false,
    comment: "Отчёт по итогам месяца для руководства",
    createdAt: new Date("2026-07-13").toISOString(),
    updatedAt: new Date("2026-07-13").toISOString(),
    boardId: "board-1",
  },
  {
    id: "ptask-3",
    date: "2026-07-14",
    startTime: "10:00",
    endTime: "12:00",
    title: "Работа над проектом",
    priority: "high",
    completed: true,
    createdAt: new Date("2026-07-14").toISOString(),
    updatedAt: new Date("2026-07-14").toISOString(),
    boardId: "board-1",
  },
  {
    id: "ptask-4",
    date: "2026-07-15",
    startTime: "11:00",
    endTime: "11:30",
    title: "Созвон с заказчиком",
    priority: "high",
    completed: false,
    comment: "Уточнить требования по новому модулю",
    createdAt: new Date("2026-07-15").toISOString(),
    updatedAt: new Date("2026-07-15").toISOString(),
    boardId: "board-1",
  },
  {
    id: "ptask-5",
    date: "2026-07-16",
    startTime: "15:00",
    endTime: "16:00",
    title: "Тренировка",
    priority: "low",
    completed: false,
    createdAt: new Date("2026-07-16").toISOString(),
    updatedAt: new Date("2026-07-16").toISOString(),
    boardId: "board-2",
  },
];

export const mockNotes: Note[] = [
  {
    id: "note-1",
    title: "План развития продукта",
    blocks: [
      { id: "b1", type: "heading1", content: "План развития продукта" },
      { id: "b2", type: "paragraph", content: "Основные направления на Q3-Q4 2026" },
      { id: "b3", type: "heading2", content: "Приоритеты" },
      { id: "b4", type: "bulletList", content: "Мобильное приложение" },
      { id: "b5", type: "bulletList", content: "Интеграция с календарями" },
      { id: "b6", type: "todo", content: "AI-ассистент для анализа трат", checked: true },
      { id: "b7", type: "todo", content: "Тёмная тема", checked: false },
      { id: "b8", type: "quote", content: "Главное — не скорость, а направление" },
    ],
    tags: ["продукт", "планы", "2026"],
    userId: "user-1",
    createdAt: new Date("2026-07-10").toISOString(),
    updatedAt: new Date("2026-07-14").toISOString(),
  },
  {
    id: "note-2",
    title: "Встреча с командой",
    blocks: [
      { id: "b9", type: "heading1", content: "Встреча с командой" },
      { id: "b10", type: "paragraph", content: "Обсуждение спринта" },
      { id: "b11", type: "numberedList", content: "Обновить статусы задач" },
      { id: "b12", type: "numberedList", content: "Согласовать дизайн" },
      { id: "b13", type: "numberedList", content: "Подготовить демо" },
      { id: "b14", type: "code", content: "const team = { members: 5, velocity: 30 };" },
    ],
    tags: ["встречи", "команда"],
    userId: "user-1",
    createdAt: new Date("2026-07-08").toISOString(),
    updatedAt: new Date("2026-07-12").toISOString(),
  },
  {
    id: "note-3",
    title: "Идеи для блога",
    blocks: [
      { id: "b15", type: "heading1", content: "Идеи для блога" },
      { id: "b16", type: "paragraph", content: "Контент-план на месяц" },
      { id: "b17", type: "heading2", content: "Темы" },
      { id: "b18", type: "bulletList", content: "Как управлять финансами" },
      { id: "b19", type: "bulletList", content: "Обзор инструментов" },
      { id: "b20", type: "todo", content: "Написать черновик", checked: true },
      { id: "b21", type: "todo", content: "Подобрать иллюстрации", checked: false },
    ],
    tags: ["блог", "контент", "идеи"],
    userId: "user-1",
    createdAt: new Date("2026-07-05").toISOString(),
    updatedAt: new Date("2026-07-11").toISOString(),
  },
];

export const mockBoardMembers: BoardMember[] = [
  {
    id: "member-1",
    boardId: "board-1",
    name: "Анна",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "member-2",
    boardId: "board-1",
    name: "Иван",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "member-3",
    boardId: "board-1",
    name: "Пётр",
    createdAt: new Date("2024-01-02").toISOString(),
  },
  {
    id: "member-4",
    boardId: "board-1",
    name: "Мария",
    createdAt: new Date("2024-01-02").toISOString(),
  },
  {
    id: "member-5",
    boardId: "board-2",
    name: "Алексей",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "member-6",
    boardId: "board-2",
    name: "Елена",
    createdAt: new Date("2024-01-01").toISOString(),
  },
];
